# Množenje matrica

---

Matrice možemo množiti na __tri različita načina__: 

\begin{align*}
\begin{bmatrix}    
1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}&=
 \begin{bmatrix}
   (1\cdot 1 + 2\cdot 4+3\cdot 1) & 1\cdot 2+2\cdot 3+3\cdot(-1))&  
    (1\cdot 0 + 2\cdot 2 + 3\cdot 1)\\
   (4\cdot 1+5\cdot 5+6\cdot 1) & (4\cdot 2+5\cdot 3+6\cdot (-1)) &  
   (4\cdot 0+5\cdot 2+6\cdot 1)\\
   (7\cdot 1+8\cdot 5+9\cdot 1) & (7\cdot 2+8\cdot 3+9\cdot (-1)) &  
   (7\cdot 0+8\cdot 2+9\cdot 1)
 \end{bmatrix} \\ \\
\begin{bmatrix}    
  1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}& =
 \begin{bmatrix} 1\\ 4\\ 7 \end{bmatrix}
 \begin{bmatrix} 1&2&0 \end{bmatrix} + 
 \begin{bmatrix} 2\\ 5\\ 8 \end{bmatrix}
 \begin{bmatrix} 4&3&2 \end{bmatrix} + 
 \begin{bmatrix} 3\\ 6\\ 9 \end{bmatrix}
 \begin{bmatrix} 1&-1&1 \end{bmatrix}\\ \\
\begin{bmatrix}    
  1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}&=
 \begin{bmatrix}
   1 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   4 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   1 \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix} &
   2 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   3 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   (-1) \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix} &
   0 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   2 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   1 \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix}
 \end{bmatrix}
\end{align*}

Formule se razlikuju u načinu prisutupa memoriji pa stoga i po brzini te u pogreškama zaokruživanja.

In [1]:
n=5
A=ones(5,5)
B=ones(5,5)
C=zeros(n,n)
for i=1:n
    for j=1:n
        for k=1:n
            C[i,j]=C[i,j]+A[i,k]*A[k,j]
        end
    end
end
C

5×5 Array{Float64,2}:
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0

In [2]:
# Ili, krace: _dot
for i=1:n
    for j=1:n
        @show C[i,j]=(A[i,:]⋅B[:,j])[]
    end
end

C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0


In [3]:
C=zeros(n,n)
for k=1:n
    for j=1:n
        for i=1:n
            C[i,j]=C[i,j]+A[i,k]*A[k,j]
            @show i,j,C[i,j]
        end
    end
end

(i, j, C[i, j]) = (1, 1, 1.0)
(i, j, C[i, j]) = (2, 1, 1.0)
(i, j, C[i, j]) = (3, 1, 1.0)
(i, j, C[i, j]) = (4, 1, 1.0)
(i, j, C[i, j]) = (5, 1, 1.0)
(i, j, C[i, j]) = (1, 2, 1.0)
(i, j, C[i, j]) = (2, 2, 1.0)
(i, j, C[i, j]) = (3, 2, 1.0)
(i, j, C[i, j]) = (4, 2, 1.0)
(i, j, C[i, j]) = (5, 2, 1.0)
(i, j, C[i, j]) = (1, 3, 1.0)
(i, j, C[i, j]) = (2, 3, 1.0)
(i, j, C[i, j]) = (3, 3, 1.0)
(i, j, C[i, j]) = (4, 3, 1.0)
(i, j, C[i, j]) = (5, 3, 1.0)
(i, j, C[i, j]) = (1, 4, 1.0)
(i, j, C[i, j]) = (2, 4, 1.0)
(i, j, C[i, j]) = (3, 4, 1.0)
(i, j, C[i, j]) = (4, 4, 1.0)
(i, j, C[i, j]) = (5, 4, 1.0)
(i, j, C[i, j]) = (1, 5, 1.0)
(i, j, C[i, j]) = (2, 5, 1.0)
(i, j, C[i, j]) = (3, 5, 1.0)
(i, j, C[i, j]) = (4, 5, 1.0)
(i, j, C[i, j]) = (5, 5, 1.0)
(i, j, C[i, j]) = (1, 1, 2.0)
(i, j, C[i, j]) = (2, 1, 2.0)
(i, j, C[i, j]) = (3, 1, 2.0)
(i, j, C[i, j]) = (4, 1, 2.0)
(i, j, C[i, j]) = (5, 1, 2.0)
(i, j, C[i, j]) = (1, 2, 2.0)
(i, j, C[i, j]) = (2, 2, 2.0)
(i, j, C[i, j]) = (3, 2, 2.0)
(i, j, C[i

In [4]:
# Ili, krace: _syrk
C=zeros(n,n)
for i=1:n
    @show C=C+A[:,i]*A[i,:]'
end

C = C + A[:, i] * (A[i, :])' = [1.0 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0 1.0]
C = C + A[:, i] * (A[i, :])' = [2.0 2.0 2.0 2.0 2.0; 2.0 2.0 2.0 2.0 2.0; 2.0 2.0 2.0 2.0 2.0; 2.0 2.0 2.0 2.0 2.0; 2.0 2.0 2.0 2.0 2.0]
C = C + A[:, i] * (A[i, :])' = [3.0 3.0 3.0 3.0 3.0; 3.0 3.0 3.0 3.0 3.0; 3.0 3.0 3.0 3.0 3.0; 3.0 3.0 3.0 3.0 3.0; 3.0 3.0 3.0 3.0 3.0]
C = C + A[:, i] * (A[i, :])' = [4.0 4.0 4.0 4.0 4.0; 4.0 4.0 4.0 4.0 4.0; 4.0 4.0 4.0 4.0 4.0; 4.0 4.0 4.0 4.0 4.0; 4.0 4.0 4.0 4.0 4.0]
C = C + A[:, i] * (A[i, :])' = [5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0]


In [5]:
C=zeros(n,n)
for j=1:n
    for k=1:n
        for i=1:n
            C[i,j]=C[i,j]+A[i,k]*A[k,j]
            @show i,j,C[i,j]
        end
    end
end

(i, j, C[i, j]) = (1, 1, 1.0)
(i, j, C[i, j]) = (2, 1, 1.0)
(i, j, C[i, j]) = (3, 1, 1.0)
(i, j, C[i, j]) = (4, 1, 1.0)
(i, j, C[i, j]) = (5, 1, 1.0)
(i, j, C[i, j]) = (1, 1, 2.0)
(i, j, C[i, j]) = (2, 1, 2.0)
(i, j, C[i, j]) = (3, 1, 2.0)
(i, j, C[i, j]) = (4, 1, 2.0)
(i, j, C[i, j]) = (5, 1, 2.0)
(i, j, C[i, j]) = (1, 1, 3.0)
(i, j, C[i, j]) = (2, 1, 3.0)
(i, j, C[i, j]) = (3, 1, 3.0)
(i, j, C[i, j]) = (4, 1, 3.0)
(i, j, C[i, j]) = (5, 1, 3.0)
(i, j, C[i, j]) = (1, 1, 4.0)
(i, j, C[i, j]) = (2, 1, 4.0)
(i, j, C[i, j]) = (3, 1, 4.0)
(i, j, C[i, j]) = (4, 1, 4.0)
(i, j, C[i, j]) = (5, 1, 4.0)
(i, j, C[i, j]) = (1, 1, 5.0)
(i, j, C[i, j]) = (2, 1, 5.0)
(i, j, C[i, j]) = (3, 1, 5.0)
(i, j, C[i, j]) = (4, 1, 5.0)
(i, j, C[i, j]) = (5, 1, 5.0)
(i, j, C[i, j]) = (1, 2, 1.0)
(i, j, C[i, j]) = (2, 2, 1.0)
(i, j, C[i, j]) = (3, 2, 1.0)
(i, j, C[i, j]) = (4, 2, 1.0)
(i, j, C[i, j]) = (5, 2, 1.0)
(i, j, C[i, j]) = (1, 2, 2.0)
(i, j, C[i, j]) = (2, 2, 2.0)
(i, j, C[i, j]) = (3, 2, 2.0)
(i, j, C[i

In [6]:
# _axpy
C=zeros(n,n)
for i=1:n
    for k=1:n
        C[:,i]=C[:,i]+A[:,k]*B[k,i]
    end
    @show C
end

C = [5.0 0.0 0.0 0.0 0.0; 5.0 0.0 0.0 0.0 0.0; 5.0 0.0 0.0 0.0 0.0; 5.0 0.0 0.0 0.0 0.0; 5.0 0.0 0.0 0.0 0.0]
C = [5.0 5.0 0.0 0.0 0.0; 5.0 5.0 0.0 0.0 0.0; 5.0 5.0 0.0 0.0 0.0; 5.0 5.0 0.0 0.0 0.0; 5.0 5.0 0.0 0.0 0.0]
C = [5.0 5.0 5.0 0.0 0.0; 5.0 5.0 5.0 0.0 0.0; 5.0 5.0 5.0 0.0 0.0; 5.0 5.0 5.0 0.0 0.0; 5.0 5.0 5.0 0.0 0.0]
C = [5.0 5.0 5.0 5.0 0.0; 5.0 5.0 5.0 5.0 0.0; 5.0 5.0 5.0 5.0 0.0; 5.0 5.0 5.0 5.0 0.0; 5.0 5.0 5.0 5.0 0.0]
C = [5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0]


## Basic Linear Algrbea Subroutines - [BLAS](http://www.netlib.org/blas/)

Na primjer, [`ddot.f`](http://www.netlib.org/lapack/explore-html/d5/df6/ddot_8f_source.html) - uočite _loop unrolling_:

```
DOUBLE PRECISION FUNCTION DDOT(N,DX,INCX,DY,INCY)
*     .. Scalar Arguments ..
      INTEGER INCX,INCY,N
*     ..
*     .. Array Arguments ..
      DOUBLE PRECISION DX(*),DY(*)
*     ..
*
*  Purpose
*  =======
*
*     forms the dot product of two vectors.
*     uses unrolled loops for increments equal to one.
*     jack dongarra, linpack, 3/11/78.
*     modified 12/3/93, array(1) declarations changed to array(*)
*
*
*     .. Local Scalars ..
      DOUBLE PRECISION DTEMP
      INTEGER I,IX,IY,M,MP1
*     ..
*     .. Intrinsic Functions ..
      INTRINSIC MOD
*     ..
      DDOT = 0.0d0
      DTEMP = 0.0d0
      IF (N.LE.0) RETURN
      IF (INCX.EQ.1 .AND. INCY.EQ.1) GO TO 20
*
*        code for unequal increments or equal increments
*          not equal to 1
*
      IX = 1
      IY = 1
      IF (INCX.LT.0) IX = (-N+1)*INCX + 1
      IF (INCY.LT.0) IY = (-N+1)*INCY + 1
      DO 10 I = 1,N
          DTEMP = DTEMP + DX(IX)*DY(IY)
          IX = IX + INCX
          IY = IY + INCY
   10 CONTINUE
      DDOT = DTEMP
      RETURN
*
*        code for both increments equal to 1
*
*
*        clean-up loop
*
   20 M = MOD(N,5)
      IF (M.EQ.0) GO TO 40
      DO 30 I = 1,M
          DTEMP = DTEMP + DX(I)*DY(I)
   30 CONTINUE
      IF (N.LT.5) GO TO 60
   40 MP1 = M + 1
      DO 50 I = MP1,N,5
          DTEMP = DTEMP + DX(I)*DY(I) + DX(I+1)*DY(I+1) +
     +            DX(I+2)*DY(I+2) + DX(I+3)*DY(I+3) + DX(I+4)*DY(I+4)
   50 CONTINUE
   60 DDOT = DTEMP
      RETURN
      END
```


## Brzina

In [7]:
function AB{T}(A::Array{T},B::Array{T})
    n=maximum(size(A))
    C=zeros(n,n)
    # C=[zeros(A[1,1]) for i=1:n, j=1:n]
    for i=1:n
        for j=1:n
            for k=1:n
                C[i,j]=C[i,j]+(A[i,k]*B[k,j])
            end
        end
    end
    C
end

AB (generic function with 1 method)

In [8]:
n=512
A=rand(n,n)
B=rand(n,n)

512×512 Array{Float64,2}:
 0.633571   0.638806   0.823324   …  0.0330132  0.695302   0.122429  
 0.384942   0.868732   0.155533      0.65922    0.0309013  0.115382  
 0.292328   0.0670797  0.98977       0.0658767  0.555164   0.760396  
 0.338825   0.516371   0.0845834     0.928322   0.378881   0.836965  
 0.259647   0.685129   0.0666353     0.381163   0.0273928  0.272035  
 0.0143432  0.0940286  0.388387   …  0.699705   0.89555    0.814354  
 0.77184    0.752138   0.527357      0.404036   0.535272   0.980112  
 0.522282   0.969617   0.783916      0.660535   0.489952   0.00228859
 0.0333244  0.578648   0.875703      0.0998287  0.668069   0.164073  
 0.704634   0.151857   0.13404       0.510641   0.481888   0.670064  
 0.494119   0.842148   0.514272   …  0.463978   0.209904   0.3597    
 0.656308   0.579936   0.637144      0.769307   0.667588   0.260416  
 0.686391   0.852244   0.698164      0.795705   0.936599   0.158294  
 ⋮                                ⋱             ⋮               

In [9]:
# Izvedite 2 puta, releventno je drugo mjerenje.
@time C=A*B

  0.562570 seconds (237.16 k allocations: 13.204 MiB)


512×512 Array{Float64,2}:
 129.118  129.627  131.469  126.386  …  132.717  138.223  136.25   131.003
 127.662  130.185  128.726  126.658     125.493  134.013  131.509  125.662
 123.911  125.386  122.388  119.729     123.186  127.651  123.917  124.957
 125.206  123.698  127.48   118.962     123.194  129.763  128.519  123.169
 123.612  120.539  123.471  115.006     122.521  127.139  127.154  120.679
 122.766  124.751  124.771  119.152  …  124.628  129.736  130.51   122.033
 125.895  129.312  127.644  121.563     129.476  131.073  129.64   124.511
 123.339  124.79   128.346  120.123     128.151  128.176  133.837  127.4  
 130.674  126.394  125.893  123.006     129.284  131.556  131.923  121.726
 127.832  129.749  128.427  119.665     124.358  131.11   130.367  125.328
 134.503  134.304  131.992  126.976  …  131.933  135.581  140.286  130.926
 130.378  128.956  129.897  123.483     128.494  133.748  137.059  129.272
 127.487  125.243  125.156  124.26      126.399  132.103  133.341  126.704

In [10]:
operacija_u_sekundi=(2*n^3)/0.012

2.2369621333333332e10

In [12]:
# Izvedite 2 puta, releventno je drugo mjerenje. Izvodjenje našeg programa 
# je značajno sporije!! 
@time AB(A,B);

  0.759360 seconds (10 allocations: 2.000 MiB)


### Blok varijanta

Da bi ubrzali naš program, potrebno je računati s blok-matricama:

In [13]:
function AB{T}(A::Array{T},B::Array{T})
    n=maximum(size(A))
    # C=zeros(n,n)
    C=[zeros(A[1,1]) for i=1:n, j=1:n]
    for i=1:n
        for j=1:n
            for k=1:n
                C[i,j]=C[i,j]+(A[i,k]*B[k,j])[]
            end
        end
    end
    C
end

AB (generic function with 1 method)

In [14]:
# Probajte k,l=32,16 i k,l=64,8. Izvedite dva puta.
k,l=64,8
Ab=[rand(k,k) for i=1:l, j=1:l]
Bb=[rand(k,k) for i=1:l, j=1:l];

In [15]:
# Ovo je bitno brze
@time C=AB(Ab,Bb);

  0.181332 seconds (59.02 k allocations: 36.809 MiB, 3.93% gc time)


## Točnost

__Apsloutna pogreška__:

$$|fl(x\cdot y)-x\cdot y|\leq O(n\varepsilon) |x|\cdot |y| \tag{1}$$

__Relativna pogreška__:

$$\frac{|fl(x\cdot y)-x\cdot y|}{|x\cdot y|}\leq O(n\varepsilon) \frac{|x|\cdot |y|}{|x\cdot y|}$$


In [16]:
n=1000000
x=rand(n)
j=round.(Int64,(rand(n)-0.5.<0.0))
y=rand(n)-0.5

1000000-element Array{Float64,1}:
  0.272691 
  0.142362 
  0.230162 
 -0.336153 
  0.375895 
 -0.457473 
 -0.482114 
  0.441799 
 -0.0657927
  0.273992 
  0.289773 
 -0.0560574
  0.254524 
  ⋮        
 -0.218526 
  0.268116 
 -0.395963 
  0.20426  
 -0.151567 
 -0.382388 
 -0.0233666
  0.194447 
 -0.323856 
 -0.480668 
  0.27343  
 -0.269285 

In [17]:
d=x⋅y

90.17667970054033

In [18]:
ab=abs.(x)⋅abs.(y)

125030.8971473302

In [19]:
# provjerimo rješenje pomocu `BigFloat` brojeva (70tak tocnih znamenki)
xbig=map(BigFloat,x)
ybig=map(BigFloat,y)

1000000-element Array{BigFloat,1}:
  2.726905121419707089813755374052561819553375244140625000000000000000000000000000e-01
  1.423619757630201210218956475728191435337066650390625000000000000000000000000000e-01
  2.301620843939504723607569758314639329910278320312500000000000000000000000000000e-01
 -3.361530568607216107324120457633398473262786865234375000000000000000000000000000e-01
  3.758945370219488602003821142716333270072937011718750000000000000000000000000000e-01
 -4.574732350149766091362835140898823738098144531250000000000000000000000000000000e-01
 -4.821140442461020469977484026458114385604858398437500000000000000000000000000000e-01
  4.417985512955813209856614776072092354297637939453125000000000000000000000000000e-01
 -6.579274949540692141169984097359701991081237792968750000000000000000000000000000e-02
  2.739924813279126514231620603823103010654449462890625000000000000000000000000000e-01
  2.897725904494989901394319531391374766826629638671875000000000000000000000000000e-01
 -5.6057

In [20]:
dbig=xbig⋅ybig

9.017667970054156286625599849366117467411985555576617254469346668388496368606866e+01

In [21]:
abserr=abs(d-dbig)

1.229537538319242675790686693097743266172544693466683884963686068658716976642609e-12

In [22]:
relerr=abserr/d

1.363476169673028402283057341765743012735368851981444696649324919263236416621367e-14

### Za matrice

Iz formule (1) za matrice slijedi

$$ |fl(A\cdot B) -A\cdot B| \leq O(n\varepsilon) |A|\cdot |B|.$$ 

In [23]:
n=256
A=rand(n,n)
B=rand(n,n).-0.5

256×256 Array{Float64,2}:
  0.447887   -0.191029   -0.153506   …  -0.161258   -0.0191771   0.230045  
 -0.441809    0.229602    0.0504582      0.147223    0.338409   -0.0387918 
 -0.29473     0.0423779  -0.309739       0.373207   -0.422239   -0.369976  
  0.340565   -0.44713    -0.128747      -0.120904   -0.415767    0.365425  
 -0.0487954   0.0601503  -0.122763       0.142439    0.277657   -0.376414  
 -0.0495049  -0.0108952  -0.303545   …   0.245551   -0.0645012  -0.326287  
  0.453067    0.393685   -0.133528       0.212838    0.376049    0.0872739 
  0.462259   -0.307569   -0.196791      -0.146221   -0.0951636   0.00424369
  0.140966    0.462592   -0.0110559     -0.305363   -0.235179   -0.327873  
 -0.410692   -0.343416   -0.476241       0.261604   -0.230021    0.390271  
 -0.161238    0.167236   -0.343634   …  -0.30156     0.123142    0.101426  
  0.319686    0.082523    0.488841       0.424495    0.169892   -0.490195  
  0.374317   -0.480403    0.0124522     -0.460281    0.0720446

In [24]:
Ab=map(BigFloat,A)
Bb=map(BigFloat,B)

256×256 Array{BigFloat,2}:
  4.478872724842386521260095832985825836658477783203125000000000000000000000000000e-01  …   2.300446421095598825701245004893280565738677978515625000000000000000000000000000e-01
 -4.418089572917007767927088934811763465404510498046875000000000000000000000000000e-01     -3.879178701699959042059617786435410380363464355468750000000000000000000000000000e-02
 -2.947301919278422221992741469875909388065338134765625000000000000000000000000000e-01     -3.699763863711011957491336943348869681358337402343750000000000000000000000000000e-01
  3.405651126654487548250926920445635914802551269531250000000000000000000000000000e-01      3.654251137037745067459582060109823942184448242187500000000000000000000000000000e-01
 -4.879538773453262479051772970706224441528320312500000000000000000000000000000000e-02     -3.764144943162130996228142976178787648677825927734375000000000000000000000000000e-01
 -4.950491997190642479154121247120201587677001953125000000000000000000000000000000e-02  

In [25]:
C=A*B
# ovo traje malo duze
Cb=Ab*Bb
abserr=abs.(C-map(Float64,Cb))

256×256 Array{Float64,2}:
 0.0          8.88178e-16  4.44089e-16  …  8.88178e-16  7.77156e-16
 8.88178e-16  4.44089e-16  4.44089e-16     1.33227e-15  4.16334e-16
 3.9968e-15   1.33227e-15  8.88178e-16     1.33227e-15  4.44089e-16
 2.66454e-15  2.22045e-15  6.66134e-16     9.99201e-16  4.44089e-16
 2.22045e-15  4.44089e-16  4.44089e-16     6.66134e-16  9.99201e-16
 4.44089e-16  8.88178e-16  4.44089e-16  …  8.88178e-16  6.66134e-16
 1.77636e-15  1.77636e-15  4.44089e-16     1.77636e-15  3.33067e-16
 8.88178e-16  0.0          4.44089e-16     8.88178e-16  2.22045e-16
 2.66454e-15  4.44089e-16  2.22045e-16     1.77636e-15  4.44089e-16
 3.10862e-15  1.11022e-16  1.66533e-16     4.44089e-16  6.66134e-16
 0.0          2.22045e-15  4.44089e-16  …  4.44089e-16  8.32667e-16
 1.77636e-15  4.44089e-16  0.0             0.0          7.77156e-16
 1.22125e-15  2.66454e-15  4.44089e-16     4.44089e-16  1.48492e-15
 ⋮                                      ⋱               ⋮          
 1.33227e-15  2.22045e

In [26]:
abs.(A)*abs.(B)*n*eps()

256×256 Array{Float64,2}:
 2.07658e-12  1.96561e-12  1.90563e-12  …  1.71123e-12  1.98011e-12
 1.97337e-12  1.80814e-12  1.83125e-12     1.68294e-12  1.81016e-12
 2.056e-12    1.91801e-12  1.99751e-12     1.8217e-12   2.03472e-12
 1.91504e-12  1.73691e-12  1.8561e-12      1.61407e-12  1.83187e-12
 1.91381e-12  1.77505e-12  1.77066e-12     1.54721e-12  1.72258e-12
 2.09122e-12  1.91201e-12  1.87997e-12  …  1.77023e-12  1.92196e-12
 1.99057e-12  1.92395e-12  1.89919e-12     1.71502e-12  1.78218e-12
 2.04168e-12  1.85883e-12  1.93555e-12     1.66564e-12  1.84132e-12
 2.12965e-12  1.90659e-12  1.91301e-12     1.8253e-12   1.92765e-12
 1.93129e-12  1.8265e-12   1.87224e-12     1.67118e-12  1.80762e-12
 2.07597e-12  1.95817e-12  1.96241e-12  …  1.72712e-12  1.88688e-12
 2.05349e-12  1.84978e-12  1.91248e-12     1.68029e-12  1.84029e-12
 2.02467e-12  1.90054e-12  1.97449e-12     1.78588e-12  1.92104e-12
 ⋮                                      ⋱               ⋮          
 2.00627e-12  1.83084e

Ovdje nije lako razabrati relativnu pogrešku pa nam treba pogodnija mjera -> __matrične i vektorske norme__.