# Množenje matrica

---

Matrice možemo množiti na __tri različita načina__: 

\begin{align*}
\begin{bmatrix}    
1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}&=
 \begin{bmatrix}
   (1\cdot 1 + 2\cdot 4+3\cdot 1) & 1\cdot 2+2\cdot 3+3\cdot(-1))&  
    (1\cdot 0 + 2\cdot 2 + 3\cdot 1)\\
   (4\cdot 1+5\cdot 5+6\cdot 1) & (4\cdot 2+5\cdot 3+6\cdot (-1)) &  
   (4\cdot 0+5\cdot 2+6\cdot 1)\\
   (7\cdot 1+8\cdot 5+9\cdot 1) & (7\cdot 2+8\cdot 3+9\cdot (-1)) &  
   (7\cdot 0+8\cdot 2+9\cdot 1)
 \end{bmatrix} \\ \\
\begin{bmatrix}    
  1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}& =
 \begin{bmatrix} 1\\ 4\\ 7 \end{bmatrix}
 \begin{bmatrix} 1&2&0 \end{bmatrix} + 
 \begin{bmatrix} 2\\ 5\\ 8 \end{bmatrix}
 \begin{bmatrix} 4&3&2 \end{bmatrix} + 
 \begin{bmatrix} 3\\ 6\\ 9 \end{bmatrix}
 \begin{bmatrix} 1&-1&1 \end{bmatrix}\\ \\
\begin{bmatrix}    
  1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}&=
 \begin{bmatrix}
   1 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   4 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   1 \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix} &
   2 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   3 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   (-1) \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix} &
   0 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   2 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   1 \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix}
 \end{bmatrix}
\end{align*}

Formule se razlikuju u načinu prisutupa memoriji pa stoga i po brzini te u pogreškama zaokruživanja.

In [1]:
n=5
A=ones(5,5)
B=ones(5,5)
C=zeros(n,n)
for i=1:n
    for j=1:n
        for k=1:n
            C[i,j]=C[i,j]+A[i,k]*A[k,j]
        end
    end
end
C

5×5 Array{Float64,2}:
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0

In [2]:
# Ili, krace: _dot
for i=1:n
    for j=1:n
        @show C[i,j]=(A[i,:]⋅B[:,j])[]
    end
end

C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0


In [3]:
C=zeros(n,n)
for k=1:n
    for j=1:n
        for i=1:n
            C[i,j]=C[i,j]+A[i,k]*A[k,j]
            @show i,j,C[i,j]
        end
    end
end

(i, j, C[i, j]) = (1, 1, 1.0)
(i, j, C[i, j]) = (2, 1, 1.0)
(i, j, C[i, j]) = (3, 1, 1.0)
(i, j, C[i, j]) = (4, 1, 1.0)
(i, j, C[i, j]) = (5, 1, 1.0)
(i, j, C[i, j]) = (1, 2, 1.0)
(i, j, C[i, j]) = (2, 2, 1.0)
(i, j, C[i, j]) = (3, 2, 1.0)
(i, j, C[i, j]) = (4, 2, 1.0)
(i, j, C[i, j]) = (5, 2, 1.0)
(i, j, C[i, j]) = (1, 3, 1.0)
(i, j, C[i, j]) = (2, 3, 1.0)
(i, j, C[i, j]) = (3, 3, 1.0)
(i, j, C[i, j]) = (4, 3, 1.0)
(i, j, C[i, j]) = (5, 3, 1.0)
(i, j, C[i, j]) = (1, 4, 1.0)
(i, j, C[i, j]) = (2, 4, 1.0)
(i, j, C[i, j]) = (3, 4, 1.0)
(i, j, C[i, j]) = (4, 4, 1.0)
(i, j, C[i, j]) = (5, 4, 1.0)
(i, j, C[i, j]) = (1, 5, 1.0)
(i, j, C[i, j]) = (2, 5, 1.0)
(i, j, C[i, j]) = (3, 5, 1.0)
(i, j, C[i, j]) = (4, 5, 1.0)
(i, j, C[i, j]) = (5, 5, 1.0)
(i, j, C[i, j]) = (1, 1, 2.0)
(i, j, C[i, j]) = (2, 1, 2.0)
(i, j, C[i, j]) = (3, 1, 2.0)
(i, j, C[i, j]) = (4, 1, 2.0)
(i, j, C[i, j]) = (5, 1, 2.0)
(i, j, C[i, j]) = (1, 2, 2.0)
(i, j, C[i, j]) = (2, 2, 2.0)
(i, j, C[i, j]) = (3, 2, 2.0)
(i, j, C[i

In [4]:
# Ili, krace: _syrk
C=zeros(n,n)
for i=1:n
    @show C=C+A[:,i]*A[i,:]'
end

C = C + A[:, i] * (A[i, :])' = [1.0 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0 1.0]
C = C + A[:, i] * (A[i, :])' = [2.0 2.0 2.0 2.0 2.0; 2.0 2.0 2.0 2.0 2.0; 2.0 2.0 2.0 2.0 2.0; 2.0 2.0 2.0 2.0 2.0; 2.0 2.0 2.0 2.0 2.0]
C = C + A[:, i] * (A[i, :])' = [3.0 3.0 3.0 3.0 3.0; 3.0 3.0 3.0 3.0 3.0; 3.0 3.0 3.0 3.0 3.0; 3.0 3.0 3.0 3.0 3.0; 3.0 3.0 3.0 3.0 3.0]
C = C + A[:, i] * (A[i, :])' = [4.0 4.0 4.0 4.0 4.0; 4.0 4.0 4.0 4.0 4.0; 4.0 4.0 4.0 4.0 4.0; 4.0 4.0 4.0 4.0 4.0; 4.0 4.0 4.0 4.0 4.0]
C = C + A[:, i] * (A[i, :])' = [5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0]


In [5]:
C=zeros(n,n)
for j=1:n
    for k=1:n
        for i=1:n
            C[i,j]=C[i,j]+A[i,k]*A[k,j]
            @show i,j,C[i,j]
        end
    end
end

(i, j, C[i, j]) = (1, 1, 1.0)
(i, j, C[i, j]) = (2, 1, 1.0)
(i, j, C[i, j]) = (3, 1, 1.0)
(i, j, C[i, j]) = (4, 1, 1.0)
(i, j, C[i, j]) = (5, 1, 1.0)
(i, j, C[i, j]) = (1, 1, 2.0)
(i, j, C[i, j]) = (2, 1, 2.0)
(i, j, C[i, j]) = (3, 1, 2.0)
(i, j, C[i, j]) = (4, 1, 2.0)
(i, j, C[i, j]) = (5, 1, 2.0)
(i, j, C[i, j]) = (1, 1, 3.0)
(i, j, C[i, j]) = (2, 1, 3.0)
(i, j, C[i, j]) = (3, 1, 3.0)
(i, j, C[i, j]) = (4, 1, 3.0)
(i, j, C[i, j]) = (5, 1, 3.0)
(i, j, C[i, j]) = (1, 1, 4.0)
(i, j, C[i, j]) = (2, 1, 4.0)
(i, j, C[i, j]) = (3, 1, 4.0)
(i, j, C[i, j]) = (4, 1, 4.0)
(i, j, C[i, j]) = (5, 1, 4.0)
(i, j, C[i, j]) = (1, 1, 5.0)
(i, j, C[i, j]) = (2, 1, 5.0)
(i, j, C[i, j]) = (3, 1, 5.0)
(i, j, C[i, j]) = (4, 1, 5.0)
(i, j, C[i, j]) = (5, 1, 5.0)
(i, j, C[i, j]) = (1, 2, 1.0)
(i, j, C[i, j]) = (2, 2, 1.0)
(i, j, C[i, j]) = (3, 2, 1.0)
(i, j, C[i, j]) = (4, 2, 1.0)
(i, j, C[i, j]) = (5, 2, 1.0)
(i, j, C[i, j]) = (1, 2, 2.0)
(i, j, C[i, j]) = (2, 2, 2.0)
(i, j, C[i, j]) = (3, 2, 2.0)
(i, j, C[i

In [6]:
# _axpy
C=zeros(n,n)
for i=1:n
    for k=1:n
        C[:,i]=C[:,i]+A[:,k]*B[k,i]
    end
    @show C
end

C = [5.0 0.0 0.0 0.0 0.0; 5.0 0.0 0.0 0.0 0.0; 5.0 0.0 0.0 0.0 0.0; 5.0 0.0 0.0 0.0 0.0; 5.0 0.0 0.0 0.0 0.0]
C = [5.0 5.0 0.0 0.0 0.0; 5.0 5.0 0.0 0.0 0.0; 5.0 5.0 0.0 0.0 0.0; 5.0 5.0 0.0 0.0 0.0; 5.0 5.0 0.0 0.0 0.0]
C = [5.0 5.0 5.0 0.0 0.0; 5.0 5.0 5.0 0.0 0.0; 5.0 5.0 5.0 0.0 0.0; 5.0 5.0 5.0 0.0 0.0; 5.0 5.0 5.0 0.0 0.0]
C = [5.0 5.0 5.0 5.0 0.0; 5.0 5.0 5.0 5.0 0.0; 5.0 5.0 5.0 5.0 0.0; 5.0 5.0 5.0 5.0 0.0; 5.0 5.0 5.0 5.0 0.0]
C = [5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0]


## Basic Linear Algrbea Subroutines - [BLAS](http://www.netlib.org/blas/)

Na primjer, [`ddot.f`](http://www.netlib.org/lapack/explore-html/d5/df6/ddot_8f_source.html) - uočite _loop unrolling_:

```
DOUBLE PRECISION FUNCTION DDOT(N,DX,INCX,DY,INCY)
*     .. Scalar Arguments ..
      INTEGER INCX,INCY,N
*     ..
*     .. Array Arguments ..
      DOUBLE PRECISION DX(*),DY(*)
*     ..
*
*  Purpose
*  =======
*
*     forms the dot product of two vectors.
*     uses unrolled loops for increments equal to one.
*     jack dongarra, linpack, 3/11/78.
*     modified 12/3/93, array(1) declarations changed to array(*)
*
*
*     .. Local Scalars ..
      DOUBLE PRECISION DTEMP
      INTEGER I,IX,IY,M,MP1
*     ..
*     .. Intrinsic Functions ..
      INTRINSIC MOD
*     ..
      DDOT = 0.0d0
      DTEMP = 0.0d0
      IF (N.LE.0) RETURN
      IF (INCX.EQ.1 .AND. INCY.EQ.1) GO TO 20
*
*        code for unequal increments or equal increments
*          not equal to 1
*
      IX = 1
      IY = 1
      IF (INCX.LT.0) IX = (-N+1)*INCX + 1
      IF (INCY.LT.0) IY = (-N+1)*INCY + 1
      DO 10 I = 1,N
          DTEMP = DTEMP + DX(IX)*DY(IY)
          IX = IX + INCX
          IY = IY + INCY
   10 CONTINUE
      DDOT = DTEMP
      RETURN
*
*        code for both increments equal to 1
*
*
*        clean-up loop
*
   20 M = MOD(N,5)
      IF (M.EQ.0) GO TO 40
      DO 30 I = 1,M
          DTEMP = DTEMP + DX(I)*DY(I)
   30 CONTINUE
      IF (N.LT.5) GO TO 60
   40 MP1 = M + 1
      DO 50 I = MP1,N,5
          DTEMP = DTEMP + DX(I)*DY(I) + DX(I+1)*DY(I+1) +
     +            DX(I+2)*DY(I+2) + DX(I+3)*DY(I+3) + DX(I+4)*DY(I+4)
   50 CONTINUE
   60 DDOT = DTEMP
      RETURN
      END
```


## Brzina

In [7]:
function AB{T}(A::Array{T},B::Array{T})
    n=maximum(size(A))
    C=zeros(n,n)
    # C=[zeros(A[1,1]) for i=1:n, j=1:n]
    for i=1:n
        for j=1:n
            for k=1:n
                C[i,j]=C[i,j]+(A[i,k]*B[k,j])
            end
        end
    end
    C
end

AB (generic function with 1 method)

In [8]:
n=512
A=rand(n,n)
B=rand(n,n)

512×512 Array{Float64,2}:
 0.953245   0.649895   0.7954     …  0.749639   0.444237   0.942584   
 0.617786   0.822348   0.188447      0.783778   0.932065   0.000684616
 0.987801   0.14901    0.409407      0.402035   0.350651   0.724008   
 0.602943   0.252232   0.185177      0.24217    0.452646   0.613671   
 0.645306   0.735263   0.716288      0.0115051  0.509277   0.393604   
 0.596057   0.182411   0.851138   …  0.842808   0.202425   0.89657    
 0.426499   0.964585   0.815547      0.112477   0.0865927  0.861642   
 0.0852511  0.949293   0.820502      0.670403   0.640875   0.297888   
 0.744653   0.0246826  0.171195      0.963058   0.158419   0.310814   
 0.937098   0.988462   0.945402      0.423923   0.202262   0.701315   
 0.765021   0.894083   0.967336   …  0.111391   0.118773   0.88267    
 0.368368   0.751697   0.352633      0.943822   0.278606   0.95263    
 0.0598177  0.131749   0.684241      0.531296   0.015505   0.704456   
 ⋮                                ⋱             ⋮  

In [9]:
# Izvedite 2 puta, releventno je drugo mjerenje.
@time C=A*B

  0.575125 seconds (237.16 k allocations: 13.204 MiB)


512×512 Array{Float64,2}:
 126.12   126.67   128.484  132.467  …  126.088  136.827  124.077  128.458
 126.494  131.048  130.065  127.963     131.675  141.246  124.322  131.38 
 122.208  124.228  123.85   125.288     124.21   132.142  122.405  124.572
 122.201  125.209  124.284  120.172     123.476  134.522  119.059  125.991
 127.391  128.45   129.092  125.946     128.782  140.326  127.331  128.744
 124.358  122.238  120.835  125.884  …  125.278  130.648  120.017  120.754
 128.175  127.993  126.542  130.051     126.873  137.551  123.697  130.064
 129.085  132.344  129.456  129.626     127.815  139.122  124.126  126.896
 130.145  125.073  125.898  127.588     131.454  137.137  121.767  126.767
 122.595  127.848  126.033  125.744     127.06   136.169  122.859  125.73 
 127.736  127.632  126.704  127.815  …  127.135  135.033  121.46   122.345
 121.089  123.193  125.175  125.664     126.369  133.132  120.925  121.924
 126.227  126.369  129.971  129.387     128.161  141.341  121.881  126.829

In [10]:
operacija_u_sekundi=(2*n^3)/0.012

2.2369621333333332e10

In [11]:
# Izvedite 2 puta, releventno je drugo mjerenje. Izvodjenje nadeg programa je znacajno sporije!! 
@time AB(A,B);

  0.770811 seconds (13.93 k allocations: 2.759 MiB)


### Blok varijanta

Da bi ubrzali naš program, potrebno je računati s blok-matricama:

In [12]:
function AB{T}(A::Array{T},B::Array{T})
    n=maximum(size(A))
    # C=zeros(n,n)
    C=[zeros(A[1,1]) for i=1:n, j=1:n]
    for i=1:n
        for j=1:n
            for k=1:n
                C[i,j]=C[i,j]+(A[i,k]*B[k,j])[]
            end
        end
    end
    C
end

AB (generic function with 1 method)

In [13]:
# Probajte k,l=32,16 i k,l=64,8. Izvedite dva puta.
k,l=64,8
Ab=[rand(k,k) for i=1:l, j=1:l]
Bb=[rand(k,k) for i=1:l, j=1:l];

In [14]:
# Ovo je bitno brze
@time C=AB(Ab,Bb);

  0.202792 seconds (59.02 k allocations: 36.809 MiB, 3.41% gc time)


## Točnost

__Apsloutna pogreška__:

$$|fl(x\cdot y)-x\cdot y|\leq O(n\varepsilon) |x|\cdot |y| \tag{1}$$

__Relativna pogreška__:

$$\frac{|fl(x\cdot y)-x\cdot y|}{|x\cdot y|}\leq O(n\varepsilon) \frac{|x|\cdot |y|}{|x\cdot y|}$$


In [15]:
n=1000000
x=rand(n)
j=round.(Int64,(rand(n)-0.5.<0.0))
y=rand(n)-0.5

1000000-element Array{Float64,1}:
 -0.132531 
  0.461915 
 -0.3395   
  0.460205 
  0.359552 
  0.385955 
 -0.345103 
  0.162785 
 -0.181097 
  0.261808 
  0.0055819
 -0.0290149
  0.348983 
  ⋮        
 -0.302772 
 -0.0673338
 -0.475681 
 -0.290859 
  0.234607 
 -0.384358 
  0.058466 
  0.346233 
 -0.465517 
 -0.158116 
 -0.364951 
 -0.464994 

In [16]:
d=x⋅y

-34.82903031572802

In [17]:
ab=abs.(x)⋅abs.(y)

125046.35901105366

In [18]:
# provjerimo rješenje pomocu `BigFloat` brojeva (70tak tocnih znamenki)
xbig=map(BigFloat,x)
ybig=map(BigFloat,y)

1000000-element Array{BigFloat,1}:
 -1.325314064526081914152655372163280844688415527343750000000000000000000000000000e-01
  4.619149667903577061167652573203667998313903808593750000000000000000000000000000e-01
 -3.394998549804673082519457238959148526191711425781250000000000000000000000000000e-01
  4.602054852678316709813088891678489744663238525390625000000000000000000000000000e-01
  3.595517762640516590266770435846410691738128662109375000000000000000000000000000e-01
  3.859552889132407127448232131428085267543792724609375000000000000000000000000000e-01
 -3.451030579408969067856105539249256253242492675781250000000000000000000000000000e-01
  1.627845346243610435976734152063727378845214843750000000000000000000000000000000e-01
 -1.810967398415412876744312598020769655704498291015625000000000000000000000000000e-01
  2.618084025063223130302958452375605702400207519531250000000000000000000000000000e-01
  5.581897222665332947144634090363979339599609375000000000000000000000000000000000e-03
 -2.9014

In [19]:
dbig=xbig⋅ybig

-3.482903031572856691391287077181080334174715769885152803246193531881702565300429e+01

In [20]:
abserr=abs(d-dbig)

5.476957995391819630002259024311363515280324619353188170256530042934173252433538e-13

In [21]:
relerr=abserr/d

-1.57252669561648594650567248116446037556861136117695740685286732763388803234494e-14

### Za matrice

Iz formule (1) za matrice slijedi

$$ |fl(A\cdot B) -A\cdot B| \leq O(n\varepsilon) |A|\cdot |B|.$$ 

In [22]:
n=256
A=rand(n,n)
B=rand(n,n).-0.5

256×256 Array{Float64,2}:
  0.337701     0.296952    -0.446472   …  -0.0922543  -0.286356    0.0702318
  0.302557    -0.380198     0.420986       0.250419    0.0773142  -0.265088 
  0.331618     0.0823184   -0.261005      -0.227917   -0.0401449   0.0453305
  0.410397     0.397704     0.402904       0.204591    0.227986   -0.367303 
 -0.00163558  -0.0631906    0.228521       0.430963   -0.339058    0.163969 
 -0.109612    -0.0333971   -0.413437   …   0.455913    0.0166391   0.297262 
 -0.346439    -0.0100697   -0.220085      -0.478658    0.327559    0.0735902
  0.280124    -0.445421     0.0496473      0.286484    0.380689   -0.220574 
  0.383737     0.253575    -0.249071      -0.182913    0.181374   -0.384163 
 -0.274277    -0.308739    -0.48053        0.431916    0.313915   -0.0659798
  0.416576    -0.433003     0.484141   …   0.234532   -0.419389   -0.203    
 -0.429688    -0.110518     0.08011       -0.142821    0.176861    0.246438 
 -0.311993     0.43861     -0.359829       0.49457

In [23]:
Ab=map(BigFloat,A)
Bb=map(BigFloat,B)

256×256 Array{BigFloat,2}:
  3.377009093012390827936997084179893136024475097656250000000000000000000000000000e-01  …   7.023184632327228449355516204377636313438415527343750000000000000000000000000000e-02
  3.025571411484127004598576604621484875679016113281250000000000000000000000000000e-01     -2.650878846576529834777602445683442056179046630859375000000000000000000000000000e-01
  3.316180360835847551470578764565289020538330078125000000000000000000000000000000e-01      4.533046557199038595342699409229680895805358886718750000000000000000000000000000e-02
  4.103972493408976074391603106050752103328704833984375000000000000000000000000000e-01     -3.673033908159071270205231485306285321712493896484375000000000000000000000000000e-01
 -1.635578663611969574276372441090643405914306640625000000000000000000000000000000e-03      1.639694301755287852984110941179096698760986328125000000000000000000000000000000e-01
 -1.096123903983226011149554324219934642314910888671875000000000000000000000000000e-01  

In [24]:
C=A*B
# ovo traje malo duze
Cb=Ab*Bb
abserr=abs.(C-map(Float64,Cb))

256×256 Array{Float64,2}:
 8.88178e-16  4.44089e-16  4.44089e-16  …  4.44089e-16  1.33227e-15
 7.77156e-16  4.44089e-16  4.71845e-16     2.22045e-16  2.88658e-15
 1.33227e-15  4.44089e-16  3.55271e-15     4.44089e-16  4.44089e-16
 1.77636e-15  8.88178e-16  2.22045e-16     8.88178e-16  1.4988e-15 
 4.44089e-16  2.77556e-16  4.44089e-16     0.0          2.22045e-15
 4.44089e-16  4.44089e-16  1.88738e-15  …  0.0          1.77636e-15
 2.66454e-15  2.77556e-16  0.0             2.22045e-15  2.22045e-15
 4.44089e-16  2.22045e-16  0.0             7.77156e-16  8.88178e-16
 1.33227e-15  8.88178e-16  2.22045e-15     1.33227e-15  2.77556e-16
 6.66134e-16  4.44089e-16  1.55431e-15     1.33227e-15  5.55112e-17
 1.44329e-15  6.66134e-16  1.11022e-15  …  8.88178e-16  1.77636e-15
 8.88178e-16  7.77156e-16  2.66454e-15     2.22045e-16  1.77636e-15
 8.88178e-16  4.44089e-16  1.77636e-15     6.66134e-16  1.33227e-15
 ⋮                                      ⋱               ⋮          
 1.77636e-15  8.88178e

In [25]:
abs.(A)*abs.(B)*n*eps()

256×256 Array{Float64,2}:
 1.76946e-12  1.81752e-12  1.92525e-12  …  1.77315e-12  1.78754e-12
 1.87812e-12  1.96421e-12  2.00409e-12     1.83474e-12  1.91795e-12
 1.78072e-12  1.76645e-12  1.91526e-12     1.80621e-12  1.86917e-12
 1.89405e-12  1.82257e-12  1.95316e-12     1.73258e-12  1.84018e-12
 1.92244e-12  1.88072e-12  1.99534e-12     1.8754e-12   1.89122e-12
 1.73194e-12  1.70247e-12  1.88384e-12  …  1.70312e-12  1.75067e-12
 1.87461e-12  1.87546e-12  1.98933e-12     1.84165e-12  1.86614e-12
 1.72959e-12  1.73572e-12  1.80613e-12     1.69281e-12  1.6813e-12 
 1.83851e-12  1.75732e-12  1.93237e-12     1.76041e-12  1.82688e-12
 1.85963e-12  1.825e-12    1.95168e-12     1.76716e-12  1.80604e-12
 1.62417e-12  1.68196e-12  1.72671e-12  …  1.59269e-12  1.63257e-12
 1.77303e-12  1.83305e-12  1.82109e-12     1.78615e-12  1.82743e-12
 1.72239e-12  1.77067e-12  1.86294e-12     1.67215e-12  1.76301e-12
 ⋮                                      ⋱               ⋮          
 1.79043e-12  1.78679e

Ovdje nije lako razabrati relativnu pogrešku pa nam treba pogodnija mjera -> __matrične i vektorske norme__.