# Množenje matrica

---

Matrice možemo množiti na __tri različita načina__: 

\begin{align*}
\begin{bmatrix}    
1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}&=
 \begin{bmatrix}
   (1\cdot 1 + 2\cdot 4+3\cdot 1) & 1\cdot 2+2\cdot 3+3\cdot(-1))&  
    (1\cdot 0 + 2\cdot 2 + 3\cdot 1)\\
   (4\cdot 1+5\cdot 5+6\cdot 1) & (4\cdot 2+5\cdot 3+6\cdot (-1)) &  
   (4\cdot 0+5\cdot 2+6\cdot 1)\\
   (7\cdot 1+8\cdot 5+9\cdot 1) & (7\cdot 2+8\cdot 3+9\cdot (-1)) &  
   (7\cdot 0+8\cdot 2+9\cdot 1)
 \end{bmatrix} \\ \\
\begin{bmatrix}    
  1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}& =
 \begin{bmatrix} 1\\ 4\\ 7 \end{bmatrix}
 \begin{bmatrix} 1&2&0 \end{bmatrix} + 
 \begin{bmatrix} 2\\ 5\\ 8 \end{bmatrix}
 \begin{bmatrix} 4&3&2 \end{bmatrix} + 
 \begin{bmatrix} 3\\ 6\\ 9 \end{bmatrix}
 \begin{bmatrix} 1&-1&1 \end{bmatrix}\\ \\
\begin{bmatrix}    
  1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}&=
 \begin{bmatrix}
   1 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   4 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   1 \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix} &
   2 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   3 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   (-1) \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix} &
   0 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   2 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   1 \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix}
 \end{bmatrix}
\end{align*}

Formule se razlikuju u načinu prisutupa memoriji pa stoga i po brzini te u pogreškama zaokruživanja.

In [1]:
n=5
A=ones(5,5)
B=ones(5,5)
C=zeros(n,n)
for i=1:n
    for j=1:n
        for k=1:n
            C[i,j]=C[i,j]+A[i,k]*A[k,j]
        end
    end
end
C

5×5 Array{Float64,2}:
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0

In [3]:
# Ili, krace: _dot
for i=1:n
    for j=1:n
        @show C[i,j]=(A[i,:]⋅B[:,j])[]
    end
end

C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0


In [4]:
C=zeros(n,n)
for k=1:n
    for j=1:n
        for i=1:n
            C[i,j]=C[i,j]+A[i,k]*A[k,j]
            @show i,j,C[i,j]
        end
    end
end

(i, j, C[i, j]) = (1, 1, 1.0)
(i, j, C[i, j]) = (2, 1, 1.0)
(i, j, C[i, j]) = (3, 1, 1.0)
(i, j, C[i, j]) = (4, 1, 1.0)
(i, j, C[i, j]) = (5, 1, 1.0)
(i, j, C[i, j]) = (1, 2, 1.0)
(i, j, C[i, j]) = (2, 2, 1.0)
(i, j, C[i, j]) = (3, 2, 1.0)
(i, j, C[i, j]) = (4, 2, 1.0)
(i, j, C[i, j]) = (5, 2, 1.0)
(i, j, C[i, j]) = (1, 3, 1.0)
(i, j, C[i, j]) = (2, 3, 1.0)
(i, j, C[i, j]) = (3, 3, 1.0)
(i, j, C[i, j]) = (4, 3, 1.0)
(i, j, C[i, j]) = (5, 3, 1.0)
(i, j, C[i, j]) = (1, 4, 1.0)
(i, j, C[i, j]) = (2, 4, 1.0)
(i, j, C[i, j]) = (3, 4, 1.0)
(i, j, C[i, j]) = (4, 4, 1.0)
(i, j, C[i, j]) = (5, 4, 1.0)
(i, j, C[i, j]) = (1, 5, 1.0)
(i, j, C[i, j]) = (2, 5, 1.0)
(i, j, C[i, j]) = (3, 5, 1.0)
(i, j, C[i, j]) = (4, 5, 1.0)
(i, j, C[i, j]) = (5, 5, 1.0)
(i, j, C[i, j]) = (1, 1, 2.0)
(i, j, C[i, j]) = (2, 1, 2.0)
(i, j, C[i, j]) = (3, 1, 2.0)
(i, j, C[i, j]) = (4, 1, 2.0)
(i, j, C[i, j]) = (5, 1, 2.0)
(i, j, C[i, j]) = (1, 2, 2.0)
(i, j, C[i, j]) = (2, 2, 2.0)
(i, j, C[i, j]) = (3, 2, 2.0)
(i, j, C[i

In [6]:
# Ili, krace: _syrk
C=zeros(n,n)
for i=1:n
    @show C=C+A[:,i]*A[i,:]'
end

C = C + A[:, i] * (A[i, :])' = [1.0 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0 1.0]
C = C + A[:, i] * (A[i, :])' = [2.0 2.0 2.0 2.0 2.0; 2.0 2.0 2.0 2.0 2.0; 2.0 2.0 2.0 2.0 2.0; 2.0 2.0 2.0 2.0 2.0; 2.0 2.0 2.0 2.0 2.0]
C = C + A[:, i] * (A[i, :])' = [3.0 3.0 3.0 3.0 3.0; 3.0 3.0 3.0 3.0 3.0; 3.0 3.0 3.0 3.0 3.0; 3.0 3.0 3.0 3.0 3.0; 3.0 3.0 3.0 3.0 3.0]
C = C + A[:, i] * (A[i, :])' = [4.0 4.0 4.0 4.0 4.0; 4.0 4.0 4.0 4.0 4.0; 4.0 4.0 4.0 4.0 4.0; 4.0 4.0 4.0 4.0 4.0; 4.0 4.0 4.0 4.0 4.0]
C = C + A[:, i] * (A[i, :])' = [5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0]


In [7]:
C=zeros(n,n)
for j=1:n
    for k=1:n
        for i=1:n
            C[i,j]=C[i,j]+A[i,k]*A[k,j]
            @show i,j,C[i,j]
        end
    end
end

(i, j, C[i, j]) = (1, 1, 1.0)
(i, j, C[i, j]) = (2, 1, 1.0)
(i, j, C[i, j]) = (3, 1, 1.0)
(i, j, C[i, j]) = (4, 1, 1.0)
(i, j, C[i, j]) = (5, 1, 1.0)
(i, j, C[i, j]) = (1, 1, 2.0)
(i, j, C[i, j]) = (2, 1, 2.0)
(i, j, C[i, j]) = (3, 1, 2.0)
(i, j, C[i, j]) = (4, 1, 2.0)
(i, j, C[i, j]) = (5, 1, 2.0)
(i, j, C[i, j]) = (1, 1, 3.0)
(i, j, C[i, j]) = (2, 1, 3.0)
(i, j, C[i, j]) = (3, 1, 3.0)
(i, j, C[i, j]) = (4, 1, 3.0)
(i, j, C[i, j]) = (5, 1, 3.0)
(i, j, C[i, j]) = (1, 1, 4.0)
(i, j, C[i, j]) = (2, 1, 4.0)
(i, j, C[i, j]) = (3, 1, 4.0)
(i, j, C[i, j]) = (4, 1, 4.0)
(i, j, C[i, j]) = (5, 1, 4.0)
(i, j, C[i, j]) = (1, 1, 5.0)
(i, j, C[i, j]) = (2, 1, 5.0)
(i, j, C[i, j]) = (3, 1, 5.0)
(i, j, C[i, j]) = (4, 1, 5.0)
(i, j, C[i, j]) = (5, 1, 5.0)
(i, j, C[i, j]) = (1, 2, 1.0)
(i, j, C[i, j]) = (2, 2, 1.0)
(i, j, C[i, j]) = (3, 2, 1.0)
(i, j, C[i, j]) = (4, 2, 1.0)
(i, j, C[i, j]) = (5, 2, 1.0)
(i, j, C[i, j]) = (1, 2, 2.0)
(i, j, C[i, j]) = (2, 2, 2.0)
(i, j, C[i, j]) = (3, 2, 2.0)
(i, j, C[i

In [8]:
# _axpy
C=zeros(n,n)
for i=1:n
    for k=1:n
        C[:,i]=C[:,i]+A[:,k]*B[k,i]
    end
    @show C
end

C = [5.0 0.0 0.0 0.0 0.0; 5.0 0.0 0.0 0.0 0.0; 5.0 0.0 0.0 0.0 0.0; 5.0 0.0 0.0 0.0 0.0; 5.0 0.0 0.0 0.0 0.0]
C = [5.0 5.0 0.0 0.0 0.0; 5.0 5.0 0.0 0.0 0.0; 5.0 5.0 0.0 0.0 0.0; 5.0 5.0 0.0 0.0 0.0; 5.0 5.0 0.0 0.0 0.0]
C = [5.0 5.0 5.0 0.0 0.0; 5.0 5.0 5.0 0.0 0.0; 5.0 5.0 5.0 0.0 0.0; 5.0 5.0 5.0 0.0 0.0; 5.0 5.0 5.0 0.0 0.0]
C = [5.0 5.0 5.0 5.0 0.0; 5.0 5.0 5.0 5.0 0.0; 5.0 5.0 5.0 5.0 0.0; 5.0 5.0 5.0 5.0 0.0; 5.0 5.0 5.0 5.0 0.0]
C = [5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0]


## Basic Linear Algrbea Subroutines - [BLAS](http://www.netlib.org/blas/)

Na primjer, [`ddot.f`](http://www.netlib.org/lapack/explore-html/d5/df6/ddot_8f_source.html) - uočite _loop unrolling_:

```
DOUBLE PRECISION FUNCTION DDOT(N,DX,INCX,DY,INCY)
*     .. Scalar Arguments ..
      INTEGER INCX,INCY,N
*     ..
*     .. Array Arguments ..
      DOUBLE PRECISION DX(*),DY(*)
*     ..
*
*  Purpose
*  =======
*
*     forms the dot product of two vectors.
*     uses unrolled loops for increments equal to one.
*     jack dongarra, linpack, 3/11/78.
*     modified 12/3/93, array(1) declarations changed to array(*)
*
*
*     .. Local Scalars ..
      DOUBLE PRECISION DTEMP
      INTEGER I,IX,IY,M,MP1
*     ..
*     .. Intrinsic Functions ..
      INTRINSIC MOD
*     ..
      DDOT = 0.0d0
      DTEMP = 0.0d0
      IF (N.LE.0) RETURN
      IF (INCX.EQ.1 .AND. INCY.EQ.1) GO TO 20
*
*        code for unequal increments or equal increments
*          not equal to 1
*
      IX = 1
      IY = 1
      IF (INCX.LT.0) IX = (-N+1)*INCX + 1
      IF (INCY.LT.0) IY = (-N+1)*INCY + 1
      DO 10 I = 1,N
          DTEMP = DTEMP + DX(IX)*DY(IY)
          IX = IX + INCX
          IY = IY + INCY
   10 CONTINUE
      DDOT = DTEMP
      RETURN
*
*        code for both increments equal to 1
*
*
*        clean-up loop
*
   20 M = MOD(N,5)
      IF (M.EQ.0) GO TO 40
      DO 30 I = 1,M
          DTEMP = DTEMP + DX(I)*DY(I)
   30 CONTINUE
      IF (N.LT.5) GO TO 60
   40 MP1 = M + 1
      DO 50 I = MP1,N,5
          DTEMP = DTEMP + DX(I)*DY(I) + DX(I+1)*DY(I+1) +
     +            DX(I+2)*DY(I+2) + DX(I+3)*DY(I+3) + DX(I+4)*DY(I+4)
   50 CONTINUE
   60 DDOT = DTEMP
      RETURN
      END
```


## Brzina

In [10]:
function AB{T}(A::Array{T},B::Array{T})
    n=maximum(size(A))
    C=zeros(n,n)
    # C=[zeros(A[1,1]) for i=1:n, j=1:n]
    for i=1:n
        for j=1:n
            for k=1:n
                C[i,j]=C[i,j]+(A[i,k]*B[k,j])
            end
        end
    end
    C
end

AB (generic function with 1 method)

In [11]:
n=512
A=rand(n,n)
B=rand(n,n)

512×512 Array{Float64,2}:
 0.0733301  0.346697   0.371834   …  0.911959   0.270426    0.669125  
 0.332561   0.0892667  0.564993      0.384258   0.842127    0.18557   
 0.612486   0.958928   0.364229      0.0396707  0.760867    0.111449  
 0.293895   0.459485   0.298356      0.0610049  0.762248    0.617197  
 0.105488   0.340348   0.29908       0.302642   0.439383    0.380055  
 0.975217   0.075212   0.421118   …  0.128808   0.945136    0.00581124
 0.90591    0.608331   0.540035      0.112111   0.997186    0.290435  
 0.986334   0.03033    0.89511       0.751453   0.0150847   0.836527  
 0.5342     0.810641   0.602333      0.065345   0.799554    0.635852  
 0.71121    0.432429   0.0608828     0.273985   0.83237     0.0740171 
 0.524956   0.0671882  0.0816648  …  0.583695   0.925883    0.699238  
 0.164304   0.943029   0.0973143     0.66638    0.830877    0.948358  
 0.272634   0.0189518  0.685769      0.416763   0.819879    0.541517  
 ⋮                                ⋱             ⋮  

In [13]:
# Izvedite 2 puta, releventno je drugo mjerenje.
@time C=A*B

  0.011743 seconds (6 allocations: 2.000 MiB)


512×512 Array{Float64,2}:
 135.923  117.138  123.487  125.978  …  132.662  128.116  128.985  128.685
 143.905  126.991  126.56   131.899     137.526  133.63   133.443  136.569
 132.498  116.464  117.025  122.757     127.325  127.971  123.09   127.151
 144.996  124.479  125.408  131.36      137.534  133.033  135.903  134.972
 137.898  119.624  124.396  126.817     133.248  131.478  131.927  132.472
 140.113  123.496  126.289  131.944  …  139.055  131.185  134.666  133.935
 133.001  114.498  121.095  119.322     131.215  127.527  124.659  127.699
 136.386  121.999  126.741  129.313     132.4    129.799  131.119  132.963
 135.195  123.347  127.02   130.593     135.576  131.142  133.691  134.317
 138.966  120.404  120.042  124.234     128.08   126.987  128.79   127.719
 137.822  119.034  125.795  128.725  …  134.602  130.355  133.111  134.047
 140.893  120.903  128.577  131.83      136.657  132.883  132.595  136.712
 144.568  122.954  127.731  131.958     138.978  133.257  132.545  138.625

In [14]:
operacija_u_sekundi=(2*n^3)/0.012

2.2369621333333332e10

In [16]:
# Izvedite 2 puta, releventno je drugo mjerenje. Izvodjenje nadeg programa je znacajno sporije!! 
@time AB(A,B);

  0.644836 seconds (10 allocations: 2.000 MiB)


### Blok varijanta

Da bi ubrzali naš program, potrebno je računati s blok-matricama:

In [17]:
function AB{T}(A::Array{T},B::Array{T})
    n=maximum(size(A))
    # C=zeros(n,n)
    C=[zeros(A[1,1]) for i=1:n, j=1:n]
    for i=1:n
        for j=1:n
            for k=1:n
                C[i,j]=C[i,j]+(A[i,k]*B[k,j])[]
            end
        end
    end
    C
end

AB (generic function with 1 method)

In [18]:
# Probajte k,l=32,16 i k,l=64,8. Izvedite dva puta.
k,l=64,8
Ab=[rand(k,k) for i=1:l, j=1:l]
Bb=[rand(k,k) for i=1:l, j=1:l];

In [21]:
# Ovo je bitno brze
@time C=AB(Ab,Bb);

  0.037018 seconds (2.18 k allocations: 34.084 MiB, 9.38% gc time)


## Točnost

__Apsloutna pogreška__:

$$|fl(x\cdot y)-x\cdot y|\leq O(n\varepsilon) |x|\cdot |y| \tag{1}$$

__Relativna pogreška__:

$$\frac{|fl(x\cdot y)-x\cdot y|}{|x\cdot y|}\leq O(n\varepsilon) \frac{|x|\cdot |y|}{|x\cdot y|}$$


In [24]:
n=1000000
x=rand(n)
j=round.(Int64,(rand(n)-0.5.<0.0))
y=rand(n)-0.5

1000000-element Array{Float64,1}:
 -0.215487  
 -0.00286195
 -0.0602622 
  0.215389  
  0.142297  
 -0.0189076 
  0.0301229 
 -0.190575  
 -0.184838  
 -0.142369  
 -0.414365  
 -0.251134  
 -0.0231188 
  ⋮         
 -0.0437855 
 -0.449899  
  0.27992   
  0.036091  
 -0.248163  
 -0.238469  
  0.313055  
  0.446292  
 -0.048592  
  0.235305  
 -0.306992  
 -0.0231596 

In [25]:
d=x⋅y

250.58362284934273

In [27]:
ab=abs.(x)⋅abs.(y)

124999.62422661562

In [28]:
# provjerimo rješenje pomocu `BigFloat` brojeva (70tak tocnih znamenki)
xbig=map(BigFloat,x)
ybig=map(BigFloat,y)

1000000-element Array{BigFloat,1}:
 -2.154870403326814010114276243257336318492889404296875000000000000000000000000000e-01
 -2.861953563286334656368126161396503448486328125000000000000000000000000000000000e-03
 -6.026215225174103018446203350322321057319641113281250000000000000000000000000000e-02
  2.153892630557487919418235833290964365005493164062500000000000000000000000000000e-01
  1.422965120729253740705644304398447275161743164062500000000000000000000000000000e-01
 -1.890758281277293839650610607350245118141174316406250000000000000000000000000000e-02
  3.012294156376005282993446598993614315986633300781250000000000000000000000000000e-02
 -1.905753915745289628347336474689655005931854248046875000000000000000000000000000e-01
 -1.848382055016331015906416723737493157386779785156250000000000000000000000000000e-01
 -1.423694754132989181982793525094166398048400878906250000000000000000000000000000e-01
 -4.143645571842360375569569441722705960273742675781250000000000000000000000000000e-01
 -2.5113

In [29]:
dbig=xbig⋅ybig

2.505836228493412273857865360699354920720169131201630247632884923147250644248629e+02

In [30]:
abserr=abs(d-dbig)

1.503956617031326168843712895196254836975236711507685274935575137078558327630162e-12

In [31]:
relerr=abserr/d

6.001815281980910884245531383933825365295000090805949017455427693041119459006345e-15

### Za matrice

Iz formule (1) za matrice slijedi

$$ |fl(A\cdot B) -A\cdot B| \leq O(n\varepsilon) |A|\cdot |B|.$$ 

In [32]:
n=256
A=rand(n,n)
B=rand(n,n).-0.5

256×256 Array{Float64,2}:
 -0.465476   -0.362447   -0.371412    …  -0.259885    0.387731   -0.130926  
  0.286845    0.484661    0.450501       -0.315905   -0.125625   -0.187761  
 -0.467355   -0.0877164   0.23837        -0.20569     0.30185    -0.274623  
 -0.493442   -0.49519     0.137859       -0.097841    0.44807    -0.185919  
  0.403914    0.405678   -0.125161        0.435781   -0.0281529  -0.068143  
 -0.22798    -0.310422    0.453953    …   0.155148    0.150394   -0.246035  
 -0.405575   -0.444131   -0.214401       -0.0830469   0.296766   -0.427269  
  0.205815    0.0995806  -0.255845       -0.411984    0.247886   -0.0803087 
 -0.0164742   0.346432   -0.484367       -0.136378    0.0522278  -0.239199  
  0.422281   -0.387257    0.242547        0.108262   -0.251705    0.340142  
  0.0446706  -0.071935   -0.445412    …   0.246117    0.156852    0.0955816 
 -0.219963   -0.414106    0.0682163      -0.0843808   0.398718    0.326021  
 -0.111892   -0.344822   -0.00750589      0.032474

In [35]:
Ab=map(BigFloat,A)
Bb=map(BigFloat,B)

256×256 Array{BigFloat,2}:
 -4.654760782851852241037704516202211380004882812500000000000000000000000000000000e-01  …  -1.309256625763857151412139501189813017845153808593750000000000000000000000000000e-01
  2.868447863454928192794568531098775565624237060546875000000000000000000000000000e-01     -1.877605552727208415575432809418998658657073974609375000000000000000000000000000e-01
 -4.673546934764334359613258129684254527091979980468750000000000000000000000000000e-01     -2.746227840728625579913568799383938312530517578125000000000000000000000000000000e-01
 -4.934415918654262434017709892941638827323913574218750000000000000000000000000000e-01     -1.859188210349356218387129047187045216560363769531250000000000000000000000000000e-01
  4.039142354747380370127984861028380692005157470703125000000000000000000000000000e-01     -6.814295792193769685241022671107202768325805664062500000000000000000000000000000e-02
 -2.279799127627335497692229182575829327106475830078125000000000000000000000000000e-01  

In [37]:
C=A*B
# ovo traje malo duze
Cb=Ab*Bb
abserr=abs.(C-map(Float64,Cb))

256×256 Array{Float64,2}:
 4.44089e-16  8.88178e-16  5.55112e-16  …  4.16334e-16  1.22125e-15
 2.22045e-15  2.22045e-16  1.77636e-15     4.44089e-16  1.11022e-16
 4.44089e-16  8.88178e-16  7.77156e-16     4.44089e-16  6.66134e-16
 1.11022e-15  8.88178e-16  4.44089e-16     4.44089e-16  1.11022e-15
 0.0          3.88578e-16  2.77556e-16     8.88178e-16  5.55112e-16
 8.88178e-16  8.88178e-16  4.44089e-16  …  8.88178e-16  1.77636e-15
 1.33227e-15  5.55112e-16  2.22045e-16     2.22045e-15  0.0        
 1.77636e-15  4.44089e-16  6.66134e-16     2.22045e-16  4.44089e-16
 2.33147e-15  8.88178e-16  1.33227e-15     2.08167e-16  8.88178e-16
 8.88178e-16  8.88178e-16  4.44089e-16     8.88178e-16  0.0        
 8.88178e-16  1.11022e-16  1.11022e-16  …  4.44089e-16  2.22045e-16
 2.22045e-16  1.9984e-15   3.33067e-16     4.44089e-16  6.10623e-16
 1.77636e-15  2.22045e-16  9.99201e-16     1.33227e-15  5.55112e-17
 ⋮                                      ⋱               ⋮          
 1.77636e-15  4.44089e

In [39]:
abs.(A)*abs.(B)*n*eps()

256×256 Array{Float64,2}:
 1.83823e-12  1.81941e-12  1.67034e-12  …  1.79087e-12  1.8669e-12 
 2.06364e-12  1.9397e-12   1.85184e-12     1.94865e-12  1.95946e-12
 1.88249e-12  2.00959e-12  1.84115e-12     1.90112e-12  1.92128e-12
 1.9085e-12   1.87936e-12  1.73376e-12     1.84628e-12  1.8627e-12 
 1.9629e-12   1.87701e-12  1.80392e-12     1.87992e-12  1.89438e-12
 1.86074e-12  1.874e-12    1.78441e-12  …  1.80283e-12  1.8719e-12 
 1.82359e-12  1.79885e-12  1.61201e-12     1.74934e-12  1.80195e-12
 1.70943e-12  1.68532e-12  1.53372e-12     1.79804e-12  1.7731e-12 
 1.82907e-12  1.76555e-12  1.61045e-12     1.77612e-12  1.8102e-12 
 1.87232e-12  1.86014e-12  1.7856e-12      1.86568e-12  1.91993e-12
 1.96359e-12  1.95859e-12  1.94606e-12  …  1.95053e-12  2.03831e-12
 1.84514e-12  1.79001e-12  1.67123e-12     1.74376e-12  1.771e-12  
 1.92841e-12  1.90429e-12  1.76564e-12     1.90905e-12  1.90514e-12
 ⋮                                      ⋱               ⋮          
 2.05045e-12  1.90972e

Ovdje nije lako razabrati relativnu pogrešku pa nam treba pogodnija mjera -> __matrične i vektorske norme__.