# Množenje matrica



Matrice možemo množiti na __tri različita načina__: 

\begin{align*}
\begin{bmatrix}    
1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}&=
 \begin{bmatrix}
   (1\cdot 1 + 2\cdot 4+3\cdot 1) & 1\cdot 2+2\cdot 3+3\cdot(-1))&  
    (1\cdot 0 + 2\cdot 2 + 3\cdot 1)\\
   (4\cdot 1+5\cdot 4+6\cdot 1) & (4\cdot 2+5\cdot 3+6\cdot (-1)) &  
   (4\cdot 0+5\cdot 2+6\cdot 1)\\
   (7\cdot 1+8\cdot 5+9\cdot 1) & (7\cdot 2+8\cdot 3+9\cdot (-1)) &  
   (7\cdot 0+8\cdot 2+9\cdot 1)
 \end{bmatrix} \\ \\
\begin{bmatrix}    
  1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}& =
 \begin{bmatrix} 1\\ 4\\ 7 \end{bmatrix}
 \begin{bmatrix} 1&2&0 \end{bmatrix} + 
 \begin{bmatrix} 2\\ 5\\ 8 \end{bmatrix}
 \begin{bmatrix} 4&3&2 \end{bmatrix} + 
 \begin{bmatrix} 3\\ 6\\ 9 \end{bmatrix}
 \begin{bmatrix} 1&-1&1 \end{bmatrix}\\ \\
\begin{bmatrix}    
  1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}&=
 \begin{bmatrix}
   1 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   4 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   1 \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix} &
   2 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   3 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   (-1) \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix} &
   0 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   2 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   1 \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix}
 \end{bmatrix}
\end{align*}

Formule se razlikuju u načinu prisutupa memoriji pa stoga i po brzini te u pogreškama zaokruživanja.

In [1]:
n=5
A=ones(5,5)
B=ones(5,5)
C=zeros(n,n)
for i=1:n
    for j=1:n
        for k=1:n
            C[i,j]=C[i,j]+A[i,k]*A[k,j]
        end
        @show i,j,C[i,j]
    end
end
C

(i, j, C[i, j]) = (1, 1, 5.0)
(i, j, C[i, j]) = (1, 2, 5.0)
(i, j, C[i, j]) = (1, 3, 5.0)
(i, j, C[i, j]) = (1, 4, 5.0)
(i, j, C[i, j]) = (1, 5, 5.0)
(i, j, C[i, j]) = (2, 1, 5.0)
(i, j, C[i, j]) = (2, 2, 5.0)
(i, j, C[i, j]) = (2, 3, 5.0)
(i, j, C[i, j]) = (2, 4, 5.0)
(i, j, C[i, j]) = (2, 5, 5.0)
(i, j, C[i, j]) = (3, 1, 5.0)
(i, j, C[i, j]) = (3, 2, 5.0)
(i, j, C[i, j]) = (3, 3, 5.0)
(i, j, C[i, j]) = (3, 4, 5.0)
(i, j, C[i, j]) = (3, 5, 5.0)
(i, j, C[i, j]) = (4, 1, 5.0)
(i, j, C[i, j]) = (4, 2, 5.0)
(i, j, C[i, j]) = (4, 3, 5.0)
(i, j, C[i, j]) = (4, 4, 5.0)
(i, j, C[i, j]) = (4, 5, 5.0)
(i, j, C[i, j]) = (5, 1, 5.0)
(i, j, C[i, j]) = (5, 2, 5.0)
(i, j, C[i, j]) = (5, 3, 5.0)
(i, j, C[i, j]) = (5, 4, 5.0)
(i, j, C[i, j]) = (5, 5, 5.0)


5×5 Array{Float64,2}:
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0

In [2]:
A

5×5 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [3]:
B

5×5 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [4]:
# Ili, krace: _dot
using LinearAlgebra
for i=1:n
    for j=1:n
        @show C[i,j]=(A[i,:]⋅B[:,j])[]
    end
end

C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0
C[i, j] = (A[i, :] ⋅ B[:, j])[] = 5.0


In [5]:
C=zeros(n,n)
for k=1:n
    for j=1:n
        for i=1:n
            C[i,j]=C[i,j]+A[i,k]*A[k,j]
            # @show i,j,C[i,j]
        end
    end
    @show C
end

C = [1.0 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0 1.0]
C = [2.0 2.0 2.0 2.0 2.0; 2.0 2.0 2.0 2.0 2.0; 2.0 2.0 2.0 2.0 2.0; 2.0 2.0 2.0 2.0 2.0; 2.0 2.0 2.0 2.0 2.0]
C = [3.0 3.0 3.0 3.0 3.0; 3.0 3.0 3.0 3.0 3.0; 3.0 3.0 3.0 3.0 3.0; 3.0 3.0 3.0 3.0 3.0; 3.0 3.0 3.0 3.0 3.0]
C = [4.0 4.0 4.0 4.0 4.0; 4.0 4.0 4.0 4.0 4.0; 4.0 4.0 4.0 4.0 4.0; 4.0 4.0 4.0 4.0 4.0; 4.0 4.0 4.0 4.0 4.0]
C = [5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0]


In [6]:
# Ili, krace: _syrk
C=zeros(n,n)
for i=1:n
    C=C+A[:,i]*A[i,:]'
    println(C)
end

[1.0 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0 1.0]
[2.0 2.0 2.0 2.0 2.0; 2.0 2.0 2.0 2.0 2.0; 2.0 2.0 2.0 2.0 2.0; 2.0 2.0 2.0 2.0 2.0; 2.0 2.0 2.0 2.0 2.0]
[3.0 3.0 3.0 3.0 3.0; 3.0 3.0 3.0 3.0 3.0; 3.0 3.0 3.0 3.0 3.0; 3.0 3.0 3.0 3.0 3.0; 3.0 3.0 3.0 3.0 3.0]
[4.0 4.0 4.0 4.0 4.0; 4.0 4.0 4.0 4.0 4.0; 4.0 4.0 4.0 4.0 4.0; 4.0 4.0 4.0 4.0 4.0; 4.0 4.0 4.0 4.0 4.0]
[5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0]


In [7]:
C=zeros(n,n)
for j=1:n
    for k=1:n
        for i=1:n
            C[i,j]=C[i,j]+A[i,k]*A[k,j]
            @show i,j,C[i,j]
        end
    end
end

(i, j, C[i, j]) = (1, 1, 1.0)
(i, j, C[i, j]) = (2, 1, 1.0)
(i, j, C[i, j]) = (3, 1, 1.0)
(i, j, C[i, j]) = (4, 1, 1.0)
(i, j, C[i, j]) = (5, 1, 1.0)
(i, j, C[i, j]) = (1, 1, 2.0)
(i, j, C[i, j]) = (2, 1, 2.0)
(i, j, C[i, j]) = (3, 1, 2.0)
(i, j, C[i, j]) = (4, 1, 2.0)
(i, j, C[i, j]) = (5, 1, 2.0)
(i, j, C[i, j]) = (1, 1, 3.0)
(i, j, C[i, j]) = (2, 1, 3.0)
(i, j, C[i, j]) = (3, 1, 3.0)
(i, j, C[i, j]) = (4, 1, 3.0)
(i, j, C[i, j]) = (5, 1, 3.0)
(i, j, C[i, j]) = (1, 1, 4.0)
(i, j, C[i, j]) = (2, 1, 4.0)
(i, j, C[i, j]) = (3, 1, 4.0)
(i, j, C[i, j]) = (4, 1, 4.0)
(i, j, C[i, j]) = (5, 1, 4.0)
(i, j, C[i, j]) = (1, 1, 5.0)
(i, j, C[i, j]) = (2, 1, 5.0)
(i, j, C[i, j]) = (3, 1, 5.0)
(i, j, C[i, j]) = (4, 1, 5.0)
(i, j, C[i, j]) = (5, 1, 5.0)
(i, j, C[i, j]) = (1, 2, 1.0)
(i, j, C[i, j]) = (2, 2, 1.0)
(i, j, C[i, j]) = (3, 2, 1.0)
(i, j, C[i, j]) = (4, 2, 1.0)
(i, j, C[i, j]) = (5, 2, 1.0)
(i, j, C[i, j]) = (1, 2, 2.0)
(i, j, C[i, j]) = (2, 2, 2.0)
(i, j, C[i, j]) = (3, 2, 2.0)
(i, j, C[i

In [8]:
# _axpy
C=zeros(n,n)
for i=1:n
    for k=1:n
        C[:,i]=C[:,i]+A[:,k]*B[k,i]
    end
    @show C
end

C = [5.0 0.0 0.0 0.0 0.0; 5.0 0.0 0.0 0.0 0.0; 5.0 0.0 0.0 0.0 0.0; 5.0 0.0 0.0 0.0 0.0; 5.0 0.0 0.0 0.0 0.0]
C = [5.0 5.0 0.0 0.0 0.0; 5.0 5.0 0.0 0.0 0.0; 5.0 5.0 0.0 0.0 0.0; 5.0 5.0 0.0 0.0 0.0; 5.0 5.0 0.0 0.0 0.0]
C = [5.0 5.0 5.0 0.0 0.0; 5.0 5.0 5.0 0.0 0.0; 5.0 5.0 5.0 0.0 0.0; 5.0 5.0 5.0 0.0 0.0; 5.0 5.0 5.0 0.0 0.0]
C = [5.0 5.0 5.0 5.0 0.0; 5.0 5.0 5.0 5.0 0.0; 5.0 5.0 5.0 5.0 0.0; 5.0 5.0 5.0 5.0 0.0; 5.0 5.0 5.0 5.0 0.0]
C = [5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0; 5.0 5.0 5.0 5.0 5.0]


`_axpy` je $y=\alpha x+y$

## Basic Linear Algebra Subroutines - [BLAS](http://www.netlib.org/blas/)

Na primjer, [`ddot.f`](http://www.netlib.org/lapack/explore-html/d5/df6/ddot_8f_source.html) - uočite _loop unrolling_ :

$x\cdot y=\sum_i x_i\cdot y_i=x_1y_1+x_2y_2+\cdots +x_ny_n$

```
DOUBLE PRECISION FUNCTION DDOT(N,DX,INCX,DY,INCY)
*     .. Scalar Arguments ..
      INTEGER INCX,INCY,N
*     ..
*     .. Array Arguments ..
      DOUBLE PRECISION DX(*),DY(*)
*     ..
*
*  Purpose
*  =======
*
*     forms the dot product of two vectors.
*     uses unrolled loops for increments equal to one.
*     jack dongarra, linpack, 3/11/78.
*     modified 12/3/93, array(1) declarations changed to array(*)
*
*
*     .. Local Scalars ..
      DOUBLE PRECISION DTEMP
      INTEGER I,IX,IY,M,MP1
*     ..
*     .. Intrinsic Functions ..
      INTRINSIC MOD
*     ..
      DDOT = 0.0d0
      DTEMP = 0.0d0
      IF (N.LE.0) RETURN
      IF (INCX.EQ.1 .AND. INCY.EQ.1) GO TO 20
*
*        code for unequal increments or equal increments
*          not equal to 1
*
      IX = 1
      IY = 1
      IF (INCX.LT.0) IX = (-N+1)*INCX + 1
      IF (INCY.LT.0) IY = (-N+1)*INCY + 1
      DO 10 I = 1,N
          DTEMP = DTEMP + DX(IX)*DY(IY)
          IX = IX + INCX
          IY = IY + INCY
   10 CONTINUE
      DDOT = DTEMP
      RETURN
*
*        code for both increments equal to 1
*
*
*        clean-up loop
*
   20 M = MOD(N,5)
      IF (M.EQ.0) GO TO 40
      DO 30 I = 1,M
          DTEMP = DTEMP + DX(I)*DY(I)
   30 CONTINUE
      IF (N.LT.5) GO TO 60
   40 MP1 = M + 1
      DO 50 I = MP1,N,5
          DTEMP = DTEMP + DX(I)*DY(I) + DX(I+1)*DY(I+1) +
     +            DX(I+2)*DY(I+2) + DX(I+3)*DY(I+3) + DX(I+4)*DY(I+4)
   50 CONTINUE
   60 DDOT = DTEMP
      RETURN
      END
```


## Brzina računanja

In [9]:
function AB(A::Array{T},B::Array{T}) where T
    n=maximum(size(A))
    C=zeros(n,n)
    # C=[zeros(A[1,1]) for i=1:n, j=1:n]
    for i=1:n
        for j=1:n
            for k=1:n
                C[i,j]=C[i,j]+(A[i,k]*B[k,j])
            end
        end
    end
    C
end

AB (generic function with 1 method)

In [10]:
import Random
Random.seed!(123)
n=512
A=rand(n,n)
B=rand(n,n)

512×512 Array{Float64,2}:
 0.559048   0.413611   0.200462    …  0.646388   0.825639    0.640068
 0.27127    0.737491   0.388564       0.921612   0.367102    0.843881
 0.122202   0.991752   0.00928114     0.93476    0.532063    0.748237
 0.738015   0.341299   0.00972434     0.857653   0.00608534  0.51896
 0.638761   0.183588   0.899151       0.561811   0.325301    0.143411
 0.0652901  0.774461   0.204975    …  0.272434   0.967018    0.748281
 0.584242   0.8112     0.357884       0.505416   0.976408    0.909415
 0.706169   0.379581   0.585808       0.704145   0.243718    0.305207
 0.528885   0.145492   0.824315       0.119248   0.842754    0.114626
 0.616225   0.490273   0.444742       0.51363    0.622275    0.419786
 0.0310208  0.0751418  0.0126417   …  0.0519811  0.855391    0.37198
 0.189579   0.732784   0.129664       0.172251   0.904828    0.536121
 0.63662    0.356225   0.307616       0.179324   0.156124    0.634727
 ⋮                                 ⋱             ⋮           
 0.3

In [11]:
# Izvedite 2 puta, releventno je drugo mjerenje.
@time C=A*B

  0.634392 seconds (2.71 M allocations: 129.547 MiB, 5.84% gc time)


512×512 Array{Float64,2}:
 125.294  137.849  128.283  133.101  …  133.101  131.957  132.134  122.44
 133.404  138.214  135.87   142.438     139.673  139.314  136.521  133.358
 132.229  134.454  129.782  137.036     133.499  133.537  136.903  130.33
 127.078  136.807  125.378  133.505     131.196  128.986  130.346  125.017
 128.451  141.94   131.234  137.336     136.539  137.014  136.038  133.836
 124.821  136.955  127.681  136.077  …  134.986  129.601  132.208  128.113
 119.38   129.222  123.028  130.429     126.979  123.017  125.454  122.223
 125.25   132.406  127.474  131.91      128.452  125.549  127.895  128.728
 130.791  142.346  134.176  142.037     139.336  133.496  138.348  131.542
 124.47   132.181  128.258  135.992     130.816  128.931  129.906  128.264
 121.735  135.365  126.839  134.212  …  128.675  127.93   129.583  128.518
 123.933  132.163  127.536  132.064     130.49   125.313  130.23   127.398
 126.002  131.855  129.414  135.508     132.142  127.721  130.686  129.248
 

In [12]:
operacija_u_sekundi=(2*n^3)/0.003

8.947848533333333e10

__Zadatak.__ Izračunajte najveći $n$ za koji dvije kvadrate matrice dimenzije $n\times n$ od `Float64` brojeva stanu u memoriju Vašeg računala. Koliko će trajati množenje tih matrica?  

In [13]:
# Izvedite 2 puta, releventno je drugo mjerenje. Izvođenje našeg programa 
# je značajno sporije!! 
@time AB(A,B);

  0.410540 seconds (56.22 k allocations: 4.935 MiB)


### Blok varijanta

Da bi ubrzali naš program boljim korištenjem cache memorije, potrebno je računati s blok-matricama (BLAS 3).

BLAS razina  |  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  operacija &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  | memorija | broj rač. operacija 
:---|:-----|:---|:---
1 | $y= \alpha x+y$  | $2n$ | $2n$
2 | $y=\alpha Ax+\beta y$ | $n^2$ | $2n^2$
3 | $C=\alpha A\cdot B+\beta C$| $3n^2$ | $2n^3$

__Zadatak.__ Proučite potprograme `daxpy.f`, `dgemmv.f` i `dgemm.f`.

In [14]:
Threads.nthreads()

8

In [15]:
function AB(A::Array{T},B::Array{T}) where T
    n=maximum(size(A))
    # C=zeros(n,n)
    C=[zero(A[1,1]) for i=1:n, j=1:n]
    for i=1:n
        for j=1:n
            for k=1:n
                C[i,j]+=(A[i,k]*B[k,j])
            end
        end
    end
    C
end

AB (generic function with 1 method)

In [16]:
# Probajte k,l=32,16 i k,l=64,8. Izvedite dva puta.
k,l=64,8
Ab=[rand(k,k) for i=1:l, j=1:l]
Bb=[rand(k,k) for i=1:l, j=1:l];

In [17]:
# Ovo je bitno brze
@time C=AB(Ab,Bb);

  0.112878 seconds (221.29 k allocations: 44.614 MiB, 11.62% gc time)


Za još veću brzinu trebalo bi koristiti sve jezgre, što `*` inače radi. 

Za korištenje Julie u višenitnom načinu u Linuxu upišite liniju

    export JULIA_NUM_THREADS=`nproc`

u datoteku  `.bashrc`. Za Windowse, postavite varijablu okruženja JULIA_NUM_THREADS na broj procesora (run msinfo32).


In [18]:
Threads.nthreads()

8

## Točnost računanja

### Osnovne računske operacije

Za operacije $\odot \in  \{+,*,/\}$ vrijedi

$$
fl(a \odot b)=(1+\varepsilon_\odot)(a\odot b),\qquad |\varepsilon_\odot|\leq \varepsilon.
$$


### Zbrajanje

Ako potpuno točno zbrojimo dva broja koji imaju (male) pogreške iz prethodnih računanja, jednakost

$$ a(1+\varepsilon_a)+b(1+\varepsilon_b)= (1+\varepsilon_{ab})(a+b)
$$

daje

$$
\varepsilon_{ab}=\frac{a\varepsilon_a+b\varepsilon_a}{a+b},
$$

pa je 

$$
|\varepsilon_{ab}|\leq \varepsilon\, \frac{|a|+  |b|}{|a+b|}.
$$

Ako su $a$ i $b$ veliki brojevi različitog predznaka i ako je $a-b$ malo, pogreška može biti velika 
(_katastrofalno kraćenje_ ).

### Skalarni produkt

Za vektore $x$ i $y$ iz $\mathbb{R}^n$, rekurzivna primjena prethodne formule daje apsloutna pogrešku

$$|fl(x\cdot y)-x\cdot y|\leq O(n\varepsilon) |x|\cdot |y| \tag{1}$$

i relativnu pogrešku

$$\frac{|fl(x\cdot y)-x\cdot y|}{|x\cdot y|}\leq O(n\varepsilon) \frac{|x|\cdot |y|}{|x\cdot y|}$$

Ukoliko su vektori $x$ i $y$ skoro okomiti, relativna pogreška može biti velika.

### Množenje matrica


Iz formule (1) za matrice $A$ i $B$ reda $n$ slijedi

$$ |fl(A\cdot B) -A\cdot B| \leq O(n\varepsilon) |A|\cdot |B|.$$ 


In [19]:
n=1_000_000
x=rand(n)
y=rand(n) .-0.5;

In [20]:
d=x⋅y

-168.72233383786136

In [21]:
ab=abs.(x)⋅abs.(y)

125087.41579739474

In [22]:
# provjerimo rješenje pomocu `BigFloat` brojeva (70tak tocnih znamenki)
xbig=map(BigFloat,x)
ybig=map(BigFloat,y)
ybig[1]

0.4830772796770104182684235638589598238468170166015625

In [23]:
dbig=xbig⋅ybig

-168.722333837861324952963879932667710278851157059295836491538060457340275632987

In [24]:
abserr=map(Float64,abs(d-dbig))

3.123424048475454e-14

In [25]:
relerr=map(Float64,abserr/d)

-1.851221458018118e-16

In [26]:
n=256
A=rand(n,n)
B=rand(n,n).-0.5;

In [27]:
Ab=map(BigFloat,A)
Bb=map(BigFloat,B);

In [28]:
C=A*B
# ovo traje malo duze
Cb=Ab*Bb
abserr=abs.(C-map(Float64,Cb))

256×256 Array{Float64,2}:
 0.0          8.88178e-16  1.94289e-16  …  1.22125e-15  3.33067e-16
 4.44089e-16  0.0          4.44089e-16     4.44089e-16  4.44089e-16
 8.88178e-16  8.88178e-16  4.44089e-16     1.33227e-15  8.88178e-16
 0.0          4.44089e-16  2.22045e-16     2.22045e-16  2.498e-16
 0.0          1.77636e-15  4.44089e-16     3.33067e-16  8.88178e-16
 4.44089e-16  8.88178e-16  8.88178e-16  …  1.16573e-15  1.72085e-15
 4.44089e-16  8.88178e-16  7.77156e-16     0.0          4.44089e-16
 0.0          8.88178e-16  4.44089e-16     4.44089e-16  6.66134e-16
 1.77636e-15  8.88178e-16  5.68989e-16     0.0          4.996e-16
 8.88178e-16  0.0          7.77156e-16     1.33227e-15  8.88178e-16
 0.0          1.33227e-15  8.88178e-16  …  2.10942e-15  1.11022e-16
 1.33227e-15  8.88178e-16  2.22045e-16     1.33227e-15  2.22045e-16
 8.88178e-16  8.88178e-16  2.22045e-16     2.63678e-16  0.0
 ⋮                                      ⋱               ⋮
 0.0          1.11022e-15  4.44089e-16     2

In [29]:
abs.(A)*abs.(B)*n*eps()

256×256 Array{Float64,2}:
 1.84106e-12  1.72578e-12  1.88512e-12  …  1.74446e-12  1.73495e-12
 1.6719e-12   1.60552e-12  1.7931e-12      1.58596e-12  1.70469e-12
 1.74514e-12  1.70415e-12  1.82548e-12     1.60188e-12  1.66942e-12
 1.83691e-12  1.79893e-12  1.94598e-12     1.73869e-12  1.77406e-12
 1.79903e-12  1.7425e-12   1.9391e-12      1.75306e-12  1.78442e-12
 1.80942e-12  1.76822e-12  1.8727e-12   …  1.69369e-12  1.67062e-12
 1.72417e-12  1.80633e-12  1.80137e-12     1.73857e-12  1.68673e-12
 1.7142e-12   1.72798e-12  1.84647e-12     1.71493e-12  1.65283e-12
 1.86284e-12  1.83902e-12  2.01703e-12     1.74358e-12  1.74056e-12
 1.79666e-12  1.8152e-12   1.861e-12       1.68721e-12  1.74388e-12
 1.84351e-12  1.78491e-12  1.89459e-12  …  1.6955e-12   1.80479e-12
 1.71624e-12  1.76455e-12  1.84257e-12     1.67885e-12  1.67151e-12
 1.65124e-12  1.6815e-12   1.79609e-12     1.65215e-12  1.618e-12
 ⋮                                      ⋱               ⋮
 1.80498e-12  1.80008e-12  1.82932

Ovdje nije lako razabrati relativnu pogrešku pa nam treba pogodnija mjera. 
U sljedećoj bilježnici objasnit ćemo  _matrične i vektorske norme_.