# Množenje matrica

---

Matrice možemo množiti na __tri različita načina__: 

\begin{align*}
\begin{bmatrix}    
1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}&=
 \begin{bmatrix}
   (1\cdot 1 + 2\cdot 4+3\cdot 1) & 1\cdot 2+2\cdot 3+3\cdot(-1))&  
    (1\cdot 0 + 2\cdot 2 + 3\cdot 1)\\
   (4\cdot 1+5\cdot 5+6\cdot 1) & (4\cdot 2+5\cdot 3+6\cdot (-1)) &  
   (4\cdot 0+5\cdot 2+6\cdot 1)\\
   (7\cdot 1+8\cdot 5+9\cdot 1) & (7\cdot 2+8\cdot 3+9\cdot (-1)) &  
   (7\cdot 0+8\cdot 2+9\cdot 1)
 \end{bmatrix} \\ \\
\begin{bmatrix}    
  1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}& =
 \begin{bmatrix} 1\\ 4\\ 7 \end{bmatrix}
 \begin{bmatrix} 1&2&0 \end{bmatrix} + 
 \begin{bmatrix} 2\\ 5\\ 8 \end{bmatrix}
 \begin{bmatrix} 4&3&2 \end{bmatrix} + 
 \begin{bmatrix} 3\\ 6\\ 9 \end{bmatrix}
 \begin{bmatrix} 1&-1&1 \end{bmatrix}\\ \\
\begin{bmatrix}    
  1& 2& 3\\
  4 &5 &6\\
  7 &8& 9
\end{bmatrix}
\begin{bmatrix}
   1&  2&  0\\
   4&  3&  2\\
   1& -1&  1
 \end{bmatrix}&=
 \begin{bmatrix}
   1 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   4 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   1 \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix} &
   2 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   3 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   (-1) \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix} &
   0 \begin{bmatrix} 1\\ 4\\ 7\end{bmatrix}+
   2 \begin{bmatrix} 2\\ 5\\ 8\end{bmatrix}+
   1 \begin{bmatrix} 3\\ 6\\ 9\end{bmatrix}
 \end{bmatrix}
\end{align*}

Formule se razlikuju u načinu prisutupa memoriji pa stoga i po brzini te u pogreškama zaokruživanja.

In [1]:
n=5
A=ones(5,5)
B=ones(5,5)
C=zeros(n,n)
for i=1:n
    for j=1:n
        for k=1:n
            C[i,j]=C[i,j]+A[i,k]*A[k,j]
        end
    end
end
C

5x5 Array{Float64,2}:
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0  5.0

In [2]:
# Ili, krace: _dot
for i=1:n
    for j=1:n
        @show C[i,j]=(A[i,:]*B[:,j])[]
    end
end

C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0
C[i,j] = (A[i,:] * B[:,j])[] = 5.0


In [3]:
C=zeros(n,n)
for k=1:n
    for j=1:n
        for i=1:n
            C[i,j]=C[i,j]+A[i,k]*A[k,j]
            @show i,j,C[i,j]
        end
    end
end

(i,j,C[i,j]) = (1,1,1.0)
(i,j,C[i,j]) = (2,1,1.0)
(i,j,C[i,j]) = (3,1,1.0)
(i,j,C[i,j]) = (4,1,1.0)
(i,j,C[i,j]) = (5,1,1.0)
(i,j,C[i,j]) = (1,2,1.0)
(i,j,C[i,j]) = (2,2,1.0)
(i,j,C[i,j]) = (3,2,1.0)
(i,j,C[i,j]) = (4,2,1.0)
(i,j,C[i,j]) = (5,2,1.0)
(i,j,C[i,j]) = (1,3,1.0)
(i,j,C[i,j]) = (2,3,1.0)
(i,j,C[i,j]) = (3,3,1.0)
(i,j,C[i,j]) = (4,3,1.0)
(i,j,C[i,j]) = (5,3,1.0)
(i,j,C[i,j]) = (1,4,1.0)
(i,j,C[i,j]) = (2,4,1.0)
(i,j,C[i,j]) = (3,4,1.0)
(i,j,C[i,j]) = (4,4,1.0)
(i,j,C[i,j]) = (5,4,1.0)
(i,j,C[i,j]) = (1,5,1.0)
(i,j,C[i,j]) = (2,5,1.0)
(i,j,C[i,j]) = (3,5,1.0)
(i,j,C[i,j]) = (4,5,1.0)
(i,j,C[i,j]) = (5,5,1.0)
(i,j,C[i,j]) = (1,1,2.0)
(i,j,C[i,j]) = (2,1,2.0)
(i,j,C[i,j]) = (3,1,2.0)
(i,j,C[i,j]) = (4,1,2.0)
(i,j,C[i,j]) = (5,1,2.0)
(i,j,C[i,j]) = (1,2,2.0)
(i,j,C[i,j]) = (2,2,2.0)
(i,j,C[i,j]) = (3,2,2.0)
(i,j,C[i,j]) = (4,2,2.0)
(i,j,C[i,j]) = (5,2,2.0)
(i,j,C[i,j]) = (1,3,2.0)
(i,j,C[i,j]) = (2,3,2.0)
(i,j,C[i,j]) = (3,3,2.0)
(i,j,C[i,j]) = (4,3,2.0)
(i,j,C[i,j]) = (5,3,2.0)


In [4]:
# Ili, krace: _syrk
C=zeros(n,n)
for i=1:n
    @show C=C+A[:,i]*A[i,:]
end

C = C + A[:,i] * A[i,:] = [1.0 1.0 1.0 1.0 1.0
 1.0 1.0 1.0 1.0 1.0
 1.0 1.0 1.0 1.0 1.0
 1.0 1.0 1.0 1.0 1.0
 1.0 1.0 1.0 1.0 1.0]
C = C + A[:,i] * A[i,:] = [2.0 2.0 2.0 2.0 2.0
 2.0 2.0 2.0 2.0 2.0
 2.0 2.0 2.0 2.0 2.0
 2.0 2.0 2.0 2.0 2.0
 2.0 2.0 2.0 2.0 2.0]
C = C + A[:,i] * A[i,:] = [3.0 3.0 3.0 3.0 3.0
 3.0 3.0 3.0 3.0 3.0
 3.0 3.0 3.0 3.0 3.0
 3.0 3.0 3.0 3.0 3.0
 3.0 3.0 3.0 3.0 3.0]
C = C + A[:,i] * A[i,:] = [4.0 4.0 4.0 4.0 4.0
 4.0 4.0 4.0 4.0 4.0
 4.0 4.0 4.0 4.0 4.0
 4.0 4.0 4.0 4.0 4.0
 4.0 4.0 4.0 4.0 4.0]
C = C + A[:,i] * A[i,:] = [5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0]


In [5]:
C=zeros(n,n)
for j=1:n
    for k=1:n
        for i=1:n
            C[i,j]=C[i,j]+A[i,k]*A[k,j]
            @show i,j,C[i,j]
        end
    end
end

(i,j,C[i,j]) = (1,1,1.0)
(i,j,C[i,j]) = (2,1,1.0)
(i,j,C[i,j]) = (3,1,1.0)
(i,j,C[i,j]) = (4,1,1.0)
(i,j,C[i,j]) = (5,1,1.0)
(i,j,C[i,j]) = (1,1,2.0)
(i,j,C[i,j]) = (2,1,2.0)
(i,j,C[i,j]) = (3,1,2.0)
(i,j,C[i,j]) = (4,1,2.0)
(i,j,C[i,j]) = (5,1,2.0)
(i,j,C[i,j]) = (1,1,3.0)
(i,j,C[i,j]) = (2,1,3.0)
(i,j,C[i,j]) = (3,1,3.0)
(i,j,C[i,j]) = (4,1,3.0)
(i,j,C[i,j]) = (5,1,3.0)
(i,j,C[i,j]) = (1,1,4.0)
(i,j,C[i,j]) = (2,1,4.0)
(i,j,C[i,j]) = (3,1,4.0)
(i,j,C[i,j]) = (4,1,4.0)
(i,j,C[i,j]) = (5,1,4.0)
(i,j,C[i,j]) = (1,1,5.0)
(i,j,C[i,j]) = (2,1,5.0)
(i,j,C[i,j]) = (3,1,5.0)
(i,j,C[i,j]) = (4,1,5.0)
(i,j,C[i,j]) = (5,1,5.0)
(i,j,C[i,j]) = (1,2,1.0)
(i,j,C[i,j]) = (2,2,1.0)
(i,j,C[i,j]) = (3,2,1.0)
(i,j,C[i,j]) = (4,2,1.0)
(i,j,C[i,j]) = (5,2,1.0)
(i,j,C[i,j]) = (1,2,2.0)
(i,j,C[i,j]) = (2,2,2.0)
(i,j,C[i,j]) = (3,2,2.0)
(i,j,C[i,j]) = (4,2,2.0)
(i,j,C[i,j]) = (5,2,2.0)
(i,j,C[i,j]) = (1,2,3.0)
(i,j,C[i,j]) = (2,2,3.0)
(i,j,C[i,j]) = (3,2,3.0)
(i,j,C[i,j]) = (4,2,3.0)
(i,j,C[i,j]) = (5,2,3.0)


In [6]:
# _axpy
C=zeros(n,n)
for i=1:n
    for k=1:n
        C[:,i]=C[:,i]+A[:,k]*B[k,i]
    end
    @show C
end

C = [5.0 0.0 0.0 0.0 0.0
 5.0 0.0 0.0 0.0 0.0
 5.0 0.0 0.0 0.0 0.0
 5.0 0.0 0.0 0.0 0.0
 5.0 0.0 0.0 0.0 0.0]
C = [5.0 5.0 0.0 0.0 0.0
 5.0 5.0 0.0 0.0 0.0
 5.0 5.0 0.0 0.0 0.0
 5.0 5.0 0.0 0.0 0.0
 5.0 5.0 0.0 0.0 0.0]
C = [5.0 5.0 5.0 0.0 0.0
 5.0 5.0 5.0 0.0 0.0
 5.0 5.0 5.0 0.0 0.0
 5.0 5.0 5.0 0.0 0.0
 5.0 5.0 5.0 0.0 0.0]
C = [5.0 5.0 5.0 5.0 0.0
 5.0 5.0 5.0 5.0 0.0
 5.0 5.0 5.0 5.0 0.0
 5.0 5.0 5.0 5.0 0.0
 5.0 5.0 5.0 5.0 0.0]
C = [5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0
 5.0 5.0 5.0 5.0 5.0]


## Basic Linear Algrbea Subroutines - [BLAS](http://www.netlib.org/blas/)

Na primjer, [`ddot.f`](http://www.netlib.org/lapack/explore-html/d5/df6/ddot_8f_source.html) - uočite _loop unrolling_:

```
DOUBLE PRECISION FUNCTION DDOT(N,DX,INCX,DY,INCY)
*     .. Scalar Arguments ..
      INTEGER INCX,INCY,N
*     ..
*     .. Array Arguments ..
      DOUBLE PRECISION DX(*),DY(*)
*     ..
*
*  Purpose
*  =======
*
*     forms the dot product of two vectors.
*     uses unrolled loops for increments equal to one.
*     jack dongarra, linpack, 3/11/78.
*     modified 12/3/93, array(1) declarations changed to array(*)
*
*
*     .. Local Scalars ..
      DOUBLE PRECISION DTEMP
      INTEGER I,IX,IY,M,MP1
*     ..
*     .. Intrinsic Functions ..
      INTRINSIC MOD
*     ..
      DDOT = 0.0d0
      DTEMP = 0.0d0
      IF (N.LE.0) RETURN
      IF (INCX.EQ.1 .AND. INCY.EQ.1) GO TO 20
*
*        code for unequal increments or equal increments
*          not equal to 1
*
      IX = 1
      IY = 1
      IF (INCX.LT.0) IX = (-N+1)*INCX + 1
      IF (INCY.LT.0) IY = (-N+1)*INCY + 1
      DO 10 I = 1,N
          DTEMP = DTEMP + DX(IX)*DY(IY)
          IX = IX + INCX
          IY = IY + INCY
   10 CONTINUE
      DDOT = DTEMP
      RETURN
*
*        code for both increments equal to 1
*
*
*        clean-up loop
*
   20 M = MOD(N,5)
      IF (M.EQ.0) GO TO 40
      DO 30 I = 1,M
          DTEMP = DTEMP + DX(I)*DY(I)
   30 CONTINUE
      IF (N.LT.5) GO TO 60
   40 MP1 = M + 1
      DO 50 I = MP1,N,5
          DTEMP = DTEMP + DX(I)*DY(I) + DX(I+1)*DY(I+1) +
     +            DX(I+2)*DY(I+2) + DX(I+3)*DY(I+3) + DX(I+4)*DY(I+4)
   50 CONTINUE
   60 DDOT = DTEMP
      RETURN
      END
```


## Brzina

In [7]:
function AB{T}(A::Array{T},B::Array{T})
    n=maximum(size(A))
    C=zeros(n,n)
    # C=[zeros(A[1,1]) for i=1:n, j=1:n]
    for i=1:n
        for j=1:n
            for k=1:n
                C[i,j]=C[i,j]+(A[i,k]*B[k,j])[]
            end
        end
    end
    C
end

AB (generic function with 1 method)

In [8]:
n=512
A=rand(n,n)
B=rand(n,n)

512x512 Array{Float64,2}:
 0.821833   0.918137   0.940666   …  0.056575    0.932546    0.725588  
 0.630099   0.706862   0.815772      0.351058    0.440589    0.299528  
 0.142566   0.410223   0.754145      0.12022     0.498769    0.659505  
 0.430291   0.700064   0.831851      0.740679    0.686761    0.028615  
 0.179295   0.196604   0.203278      0.846761    0.0869362   0.466671  
 0.115814   0.925872   0.442315   …  0.52172     0.572264    0.638623  
 0.862459   0.958138   0.630085      0.916138    0.90126     0.49676   
 0.610977   0.777992   0.508909      0.176253    0.102278    0.53913   
 0.0993387  0.296397   0.679443      0.532448    0.692262    0.0323592 
 0.717998   0.59103    0.947941      0.554862    0.00357866  0.00237037
 0.831551   0.868238   0.0084147  …  0.377859    0.456414    0.0619908 
 0.895615   0.257791   0.683536      0.768412    0.395794    0.760618  
 0.306542   0.306844   0.567206      0.249304    0.865572    0.988     
 ⋮                                ⋱   

In [10]:
# Izvedite 2 puta, releventno je drugo mjerenje.
@time C=A*B

512x512 Array{Float64,2}:
 124.22   121.67   123.723  118.206  …  129.856  122.58   123.96   131.65 
 122.58   122.329  119.469  116.18      132.676  127.91   124.067  132.279
 133.431  126.606  128.868  123.671     135.147  133.06   132.232  139.944
 126.385  120.442  120.557  119.978     125.248  127.046  126.736  133.176
 124.969  123.411  122.084  120.273     132.116  127.345  128.868  135.722
 126.611  122.107  124.018  120.16   …  129.335  123.883  128.285  133.84 
 124.167  121.188  120.113  117.263     127.265  126.264  124.121  129.611
 128.717  126.656  125.409  120.703     133.986  129.496  125.816  133.537
 126.315  123.593  126.253  118.929     128.705  126.362  126.839  131.27 
 127.689  124.752  129.902  122.192     130.071  131.234  129.134  136.548
 122.096  119.281  121.633  118.146  …  128.703  124.714  126.191  132.505
 128.348  126.828  129.997  121.927     135.346  130.689  130.852  139.712
 124.696  125.23   126.732  120.249     126.97   129.912  128.433  134.312

0.012068 seconds (9 allocations: 2.000 MB)


In [11]:
operacija_u_sekundi=(2*n^3)/0.012

2.2369621333333332e10

In [13]:
# Izvedite 2 puta, releventno je drugo mjerenje. Izvodjenje nadeg programa je znacajno sporije!! 
@time AB(A,B);

  0.452341 seconds (6 allocations: 2.000 MB)


### Blok varijanta

Da bi ubrzali naš program, potrebno je računati s blok-matricama:

In [14]:
function AB{T}(A::Array{T},B::Array{T})
    n=maximum(size(A))
    # C=zeros(n,n)
    C=[zeros(A[1,1]) for i=1:n, j=1:n]
    for i=1:n
        for j=1:n
            for k=1:n
                C[i,j]=C[i,j]+(A[i,k]*B[k,j])[]
            end
        end
    end
    C
end

AB (generic function with 1 method)

In [19]:
# Probajte k,l=32,16 i k,l=64,8. Izvedite dva puta.
k,l=64,8
Ab=[rand(k,k) for i=1:l, j=1:l]
Bb=[rand(k,k) for i=1:l, j=1:l];

In [20]:
# Ovo je bitno brze
@time C=AB(Ab,Bb);

  0.034764 seconds (3.21 k allocations: 34.091 MB, 2.76% gc time)


## Točnost

__Apsloutna pogreška__:

$$|fl(x\cdot y)-x\cdot y|\leq O(n\varepsilon) |x|\cdot |y| \tag{1}$$

__Relativna pogreška__:

$$\frac{|fl(x\cdot y)-x\cdot y|}{|x\cdot y|}\leq O(n\varepsilon) \frac{|x|\cdot |y|}{|x\cdot y|}$$


In [21]:
n=1000000
x=rand(n)
j=round(Int64,(rand(n)-0.5.<0.0))
y=rand(n)-0.5

1000000-element Array{Float64,1}:
  0.274114  
 -0.00445511
  0.204019  
  0.0750042 
 -0.473216  
  0.0867654 
  0.212141  
 -0.456045  
  0.0938861 
  0.127901  
 -0.123505  
 -0.327896  
 -0.430919  
  ⋮         
 -0.205923  
 -0.493402  
  0.227429  
 -0.33811   
 -0.294926  
  0.424998  
 -0.283327  
  0.00146654
 -0.365175  
  0.251788  
 -0.0867376 
  0.247481  

In [22]:
d=x⋅y

114.9668029447452

In [23]:
ab=abs(x)⋅abs(y)

125091.24888631649

In [26]:
# provjerimo rješenje pomocu `BigFloat` brojeva (70tak tocnih znamenki)
xbig=map(BigFloat,x)
ybig=map(BigFloat,y)

1000000-element Array{BigFloat,1}:
  2.741137864225189346711886173579841852188110351562500000000000000000000000000000e-01
 -4.455111348939944093672238523140549659729003906250000000000000000000000000000000e-03
  2.040193376477101860899665553006343543529510498046875000000000000000000000000000e-01
  7.500424304992248103474139497848227620124816894531250000000000000000000000000000e-02
 -4.732155021885999790498544825823046267032623291015625000000000000000000000000000e-01
  8.676537258135263996905450767371803522109985351562500000000000000000000000000000e-02
  2.121406042494866639458450663369148969650268554687500000000000000000000000000000e-01
 -4.560450945361316232862236574874259531497955322265625000000000000000000000000000e-01
  9.388606353988393493636976927518844604492187500000000000000000000000000000000000e-02
  1.279014645096891999997978928149677813053131103515625000000000000000000000000000e-01
 -1.235053327513537801962684170575812458992004394531250000000000000000000000000000e-01
 -3.2789

In [27]:
dbig=xbig⋅ybig

1.149668029447489690669318915740006743301761041199702904636353233223250436267904e+02

In [28]:
abserr=abs(d-dbig)

3.77194326588869321878536838411193247029046363532332232504362679037512862123549e-12

In [29]:
relerr=abserr/d

3.280897762897300719276610541988996766262229428196228955348699869908750145667632e-14

### Za matrice

Iz formule (1) za matrice slijedi

$$ |fl(A\cdot B) -A\cdot B| \leq O(n\varepsilon) |A|\cdot |B|.$$ 

In [30]:
n=256
A=rand(n,n)
B=rand(n,n).-0.5

256x256 Array{Float64,2}:
 -0.470857   -0.455221    0.275552   …   0.327859   -0.417586    0.0166681
 -0.25484     0.155889    0.378858       0.331274   -0.370995    0.481542 
  0.0726968   0.283308    0.0741887      0.101248    0.214586   -0.106112 
 -0.208293   -0.0975971  -0.239129      -0.0146071   0.311117    0.45673  
  0.0983488   0.172174    0.314158       0.4473      0.344466    0.0943849
  0.036048    0.0499653   0.422393   …   0.177828   -0.42032     0.0951054
  0.263081    0.0292314   0.0449048      0.298692   -0.128748   -0.151325 
  0.124308    0.234584   -0.157553       0.0400216  -0.434337   -0.325796 
  0.0485226   0.274485   -0.182777      -0.320566   -0.229028   -0.493582 
 -0.106375   -0.295238   -0.444923      -0.0562341  -0.295495    0.0301406
  0.152119    0.30993    -0.162109   …   0.36677     0.180644   -0.139247 
 -0.1639     -0.254233    0.238553      -0.180934   -0.120426    0.0928048
 -0.19582     0.0937437  -0.384814      -0.485034   -0.464458   -0.191769 

In [31]:
Ab=[BigFloat(A[i,j]) for i=1:n, j=1:n]
Bb=[BigFloat(B[i,j]) for i=1:n, j=1:n]

256x256 Array{BigFloat,2}:
 -4.708568980523661906545385136269032955169677734375000000000000000000000000000000e-01  …   1.666813133821620773744598409393802285194396972656250000000000000000000000000000e-02
 -2.548402165315555301106087426887825131416320800781250000000000000000000000000000e-01      4.815417093995009167883836198598146438598632812500000000000000000000000000000000e-01
  7.269675210282833255348577949916943907737731933593750000000000000000000000000000e-02     -1.061123038069027302299218717962503433227539062500000000000000000000000000000000e-01
 -2.082925827819124275919193678419105708599090576171875000000000000000000000000000e-01      4.567296136669132256002967551467008888721466064453125000000000000000000000000000e-01
  9.834882990446791595218201109673827886581420898437500000000000000000000000000000e-02      9.438491813567995158962276036618277430534362792968750000000000000000000000000000e-02
  3.604796126957077184727040730649605393409729003906250000000000000000000000000000e-02  

In [33]:
C=A*B
# ovo traje malo duze
Cb=Ab*Bb
abserr=abs(C-map(Float64,Cb))

256x256 Array{Float64,2}:
 0.0          2.22045e-16  0.0          …  6.10623e-16  8.88178e-16
 1.77636e-15  1.16573e-15  0.0             1.22125e-15  9.02056e-16
 1.77636e-15  2.22045e-16  1.33227e-15     1.77636e-15  1.33227e-15
 0.0          4.44089e-16  1.77636e-15     0.0          8.32667e-16
 8.88178e-16  4.44089e-16  1.33227e-15     4.44089e-16  2.22045e-15
 1.33227e-15  8.32667e-16  2.66454e-15  …  1.77636e-15  0.0        
 8.88178e-16  1.80411e-16  9.71445e-17     8.88178e-16  8.88178e-16
 4.44089e-16  2.22045e-16  1.33227e-15     1.77636e-15  2.88658e-15
 8.88178e-16  1.11022e-16  7.10543e-15     8.88178e-16  2.66454e-15
 0.0          2.22045e-15  6.66134e-16     8.88178e-16  4.71845e-16
 8.88178e-16  6.66134e-16  8.88178e-16  …  8.88178e-16  8.88178e-16
 0.0          2.77556e-16  1.33227e-15     2.66454e-15  8.88178e-16
 1.33227e-15  1.33227e-15  8.88178e-16     8.88178e-16  3.33067e-16
 ⋮                                      ⋱               ⋮          
 8.88178e-16  5.55112e

In [34]:
abs(A)*abs(B)*n*eps()

256x256 Array{Float64,2}:
 1.73679e-12  1.72522e-12  1.71681e-12  …  1.69876e-12  1.75595e-12
 1.86373e-12  1.8991e-12   1.877e-12       1.93154e-12  1.87055e-12
 1.83538e-12  1.84346e-12  1.78194e-12     1.83964e-12  1.8561e-12 
 1.78351e-12  1.74422e-12  1.76799e-12     1.7629e-12   1.78247e-12
 1.89486e-12  1.92846e-12  1.86736e-12     1.89822e-12  1.91754e-12
 1.87823e-12  1.86133e-12  1.85502e-12  …  1.83045e-12  1.86143e-12
 1.91132e-12  1.97382e-12  1.90198e-12     1.90213e-12  1.97255e-12
 1.81007e-12  1.87826e-12  1.84934e-12     1.81852e-12  1.81559e-12
 1.83333e-12  1.82341e-12  1.90358e-12     1.8515e-12   1.81562e-12
 1.77578e-12  1.82164e-12  1.76258e-12     1.8044e-12   1.78313e-12
 1.83208e-12  1.80182e-12  1.85918e-12  …  1.8767e-12   1.88494e-12
 1.67877e-12  1.77593e-12  1.74116e-12     1.69615e-12  1.78817e-12
 1.81057e-12  1.83246e-12  1.82782e-12     1.80781e-12  1.7739e-12 
 ⋮                                      ⋱               ⋮          
 1.76341e-12  1.82534e

Ovdje nije lako razabrati relativnu pogrešku pa nam treba pogodnija mjera -> __matrične i vektorske norme__.