# QR rastav

---

__QR rastav__ matrice $A$ tipa $m\times n$,  $m\geq n$,
glasi

$$
A=QR, 
$$

pri čemu je $Q$ __ortonormirana matrica__ dimenzije $m\times m$, odnosno
\[
Q^TQ=Q Q^T=I,
\]
a $R$ je $m\times n$ gornje trokutasta matrica.

Ortonormiranu matricu kraće zovemo i __ortogonalna matrica__.

Na primjer,

$$
\begin{bmatrix} a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33} \\
a_{41} & a_{42} & a_{43} \\
a_{51} & a_{52} & a_{53}
\end{bmatrix}
=
\begin{bmatrix}
q_{11} & q_{12} & q_{13} & q_{14} & q_{15} \\
q_{21} & q_{22} & q_{23} & q_{24} & q_{25} \\
q_{31} & q_{32} & q_{33} & q_{34} & q_{35} \\
q_{41} & q_{42} & q_{43} & q_{44} & q_{45} \\
q_{51} & q_{52} & q_{53} & q_{54} & q_{55}
\end{bmatrix}
\begin{bmatrix}
r_{11} & r_{12} & r_{13} \\
0 & r_{22} & r_{23} \\
0 & 0 & r_{33} \\
0 & 0 & 0 \\
0 & 0 & 0 
\end{bmatrix}. \tag{1}
$$

S (1) je definiram i __ekonomični QR rastav__

$$
\begin{bmatrix} a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33} \\
a_{41} & a_{42} & a_{43} \\
a_{51} & a_{52} & a_{53}
\end{bmatrix}
=
\begin{bmatrix}
q_{11} & q_{12} & q_{13} \\
q_{21} & q_{22} & q_{23} \\
q_{31} & q_{32} & q_{33} \\
q_{41} & q_{42} & q_{43} \\
q_{51} & q_{52} & q_{53}
\end{bmatrix}
\begin{bmatrix}
r_{11} & r_{12} & r_{13} \\
0 & r_{22} & r_{23} \\
0 & 0 & r_{33}
\end{bmatrix}. \tag{2}
$$


Izjednačavanje stupaca počevši od prvog daje: 

\begin{align}
t&=a_{:1}\\
r_{11}&=\|t\|_2 \\
q_{:1}&=t\frac{1}{r_{11}}\\
r_{12}&= q_{:1}^Ta_{:1} \\
t&=a_{:2}-q_{:1}r_{12} \\
r_{22}&=\|t\|_2 \\
q_{:2}&=t\frac{1}{r_{22}} \\
r_{13}&=q_{:1}^Ta_{:3} \\
r_{23}&=q_{:2}^Ta_{:3} \\
t&=a_{:3}-q_{:1}r_{13}-q_{:2}r_{23}\\
r_{33}&=\|t\|_2 \\
q_{:3}&=t\frac{1}{r_{33}}.
\end{align}

Indukcijom slijedi __Gram-Schmidt-ov postupak ortogonalizacije__.

In [1]:
function myGramSchmidtQR{T}(A::Array{T})
    m,n=size(A)
    R=zeros(Float64,n,n)
    Q=Array(Float64,m,n)
    R[1,1]=norm(A[:,1])
    Q[:,1]=A[:,1]/R[1,1]
    for k=2:n
        for i=1:k-1
            R[i,k]=Q[:,i]⋅A[:,k]
        end
        t=A[:,k]-sum([R[i,k]*Q[:,i] for i=1:k-1])
        R[k,k]=norm(t)
        Q[:,k]=t/R[k,k]
    end
    Q,R
end 

myGramSchmidtQR (generic function with 1 method)

In [2]:
A=rand(8,5)
Q,R=myGramSchmidtQR(A)

(
[0.0878571 0.427132 … -0.237135 -0.156486; 0.630281 -0.70425 … -0.186113 -0.0584778; … ; 0.271373 0.322519 … -0.366567 0.646157; 0.295431 0.172138 … 0.31371 -0.153881],

[1.41466 1.41819 … 0.91099 1.17717; 0.0 0.911875 … 0.698977 0.774325; … ; 0.0 0.0 … 0.587086 0.281292; 0.0 0.0 … 0.0 0.478971])

In [3]:
A-Q*R

8×5 Array{Float64,2}:
  0.0          0.0           0.0          -5.55112e-17   0.0        
  0.0          5.55112e-17   0.0          -2.08167e-17  -2.77556e-17
  0.0          0.0          -2.42861e-17  -6.93889e-18   0.0        
  0.0          0.0           0.0           0.0           0.0        
  5.55112e-17  0.0           0.0           0.0           0.0        
  0.0          0.0           0.0          -1.11022e-16   0.0        
 -5.55112e-17  0.0           0.0           0.0           0.0        
  5.55112e-17  0.0           2.77556e-17   5.55112e-17  -5.55112e-17

In [4]:
Q'*Q

5×5 Array{Float64,2}:
  1.0           5.2932e-18    2.09248e-16   1.64332e-16  -1.66533e-16
  5.2932e-18    1.0          -4.59682e-17  -1.39382e-16   1.38778e-16
  2.09248e-16  -4.59682e-17   1.0          -5.72697e-17  -3.88578e-16
  1.64332e-16  -1.39382e-16  -5.72697e-17   1.0           8.32667e-17
 -1.66533e-16   1.38778e-16  -3.88578e-16   8.32667e-17   1.0        

Algoritam `myGramSchmidtQR()` je numerički nestabilan pa je bolje koristiti _modificirani Gram-Schmidt-ov algoritam_ ili _Householder-ove reflektore_ ili _Givens-ove rotacije_ (vidi [Matrix Computations, poglavlje 5][GVL13]).

[GVL13]: https://books.google.hr/books?id=X5YfsuCWpxMC&printsec=frontcover&hl=hr#v=onepage&q&f=false "G. Golub and C. F Van Loan, 'Matrix Computations', 4th Edition, John Hopkins, Baltimore, 2013"

## Householderovi reflektori

__QR rastav vektora__ $x$ jednak je

$$
H \begin{bmatrix} x_1 \\ x_2 \\ \vdots \\ x_m 
\end{bmatrix}  =r,
$$

gdje je 

$$
H=I - \frac{2}{v^Tv}v v^T, \qquad  
v=\begin{bmatrix}
x_1\pm \|x\|_2 \\ x_2 \\ x_3 \\ \vdots \\ x_m
\end{bmatrix}.
$$ 

__Householderov reflektor__ $H$ je __simetrična__ i __ortogonalna__ matrica (dokažite!). Ovisno o izboru predznaka u definicije vektora $v$ vrijedi

$$
r=\begin{bmatrix} \mp \|x\| \\ 0 \\ \vdots \\ 0
\end{bmatrix}
$$

Zbog numeričke stabilnost se najčešće uzima

$$
v_1=x_1+\mathop{\mathrm{sign}} (x_1) \|x\|_2.
$$

Matrica $H$ se __ne računa eksplicitno__ već se produkt $Hx$ računa po formuli

$$
Hx=x-v\frac{2v^Tx}{v^Tv}
$$

za koju je potrebno $O(6m)$ operacija.

In [5]:
function myHouseholderVector{T}(x::Array{T})
    # Vraca v
    v=deepcopy(x)
    v[1]=x[1]+sign(x[1])*norm(x)
    v
end

myHouseholderVector (generic function with 1 method)

In [6]:
x=rand(8)
v=myHouseholderVector(x)
β=(2/(v⋅v))*(v⋅x)
x-β*v

8-element Array{Float64,1}:
 -1.90116
  0.0    
  0.0    
  0.0    
  0.0    
  0.0    
  0.0    
  0.0    

In [7]:
norm(x)

1.9011637385678988

QR rastav matrice se računa rekurzivnim QR rastavom vektora pomoću Householderovih reflektora:

In [8]:
function myHouseholderQR{T}(A1::Array{T})
    # Vraca Q i R
    A=deepcopy(A1)
    m,n=size(A)
    # R=zeros(Float64,m,n)
    Q=eye(Float64,m,m)
    for k=1:n
        v=myHouseholderVector(A[k:m,k])
        β=(2/(v⋅v))*v
        A[k:m,k:n]=A[k:m,k:n]-β*(v'*A[k:m,k:n])
        Q[k:m,:]=Q[k:m,:]-β*(v'*Q[k:m,:])
    end
    R=triu(A)
    Q',R
end
    

myHouseholderQR (generic function with 1 method)

In [9]:
A=rand(8,5)

8×5 Array{Float64,2}:
 0.177083   0.218212   0.402715  0.96175    0.352683
 0.0109619  0.860576   0.78396   0.0597564  0.496637
 0.769124   0.115343   0.24995   0.340618   0.687614
 0.158432   0.539803   0.466003  0.972886   0.694406
 0.756395   0.752133   0.69224   0.803256   0.673002
 0.0824303  0.944943   0.520098  0.562432   0.329217
 0.753034   0.0116682  0.437111  0.0105164  0.079305
 0.331772   0.303652   0.671118  0.43314    0.730943

In [10]:
Q,R=myHouseholderQR(A)

(
[-0.128328 -0.0869354 … -0.375423 -0.435086; -0.00794384 -0.584304 … -0.0510726 -0.444599; … ; -0.545706 0.256528 … 0.427445 -0.0718147; -0.240428 -0.0909938 … -0.141419 0.525392],

[-1.37993 -0.709199 … -1.00922 -1.11977; 0.0 -1.46318 … -0.941291 -0.823224; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0])

In [11]:
Q'*A

8×5 Array{Float64,2}:
 -1.37993      -0.709199     -1.06113      -1.00922      -1.11977    
 -5.7013e-19   -1.46318      -1.03293      -0.941291     -0.823224   
  5.15603e-18   1.70553e-16   0.504603      0.145293      0.298461   
 -1.16249e-16   2.81716e-16  -6.16555e-17  -1.10212      -0.338898   
  3.71063e-17   1.23978e-16   1.0704e-16    1.5301e-16    0.540761   
  1.50379e-16   8.11763e-17   2.46153e-16   2.41403e-16   3.33067e-16
  1.57764e-17  -6.56442e-17   1.10388e-16   8.5463e-17    5.55112e-17
 -7.07284e-17  -3.20889e-16  -1.63287e-16  -2.15563e-16  -1.66533e-16

Program `myHouseholderQR()` je ilustrativan. Profesionalni programi imaju sljedeća svojstva:

* računaju s blok matricama (uobičajena dimenzija bloka je 32 ili 64),
* izračuna se vektor $\hat v=v/v_1$. Vrijedi $\hat v_1=1$, dok se ostali elemenenti vektora $\hat v$ spremaju u strogi donji trokut matrice $A$,
* ako se traži matrica $Q$, akumulacija se vrši unatrag koristeći spremljene vektore $v$ (tako se smanjuje broj operacija),
* postoji opcija vraćanja ekonomičnog rastava,
* postoji opcija računanja s __pivotiranjem__ - u svakom koraku se na prvo mjesto dovede stupac s najvećom normom pa je 

$$
AP=QR.
$$

Vrijedi

$$
|R_{kk}|\geq |R_{k+1,k+1}|
$$

pa se može utvrditi i numerički rank matrice.

In [12]:
Q1,R1=qr(A,thin=true)

(
[-0.128328 -0.0869354 … -0.634699 -0.33697; -0.00794384 -0.584304 … 0.497022 0.135816; … ; -0.545706 0.256528 … 0.30321 -0.537367; -0.240428 -0.0909938 … -0.0110051 0.35621],

[-1.37993 -0.709199 … -1.00922 -1.11977; 0.0 -1.46318 … -0.941291 -0.823224; … ; 0.0 0.0 … -1.10212 -0.338898; 0.0 0.0 … 0.0 0.540761])

In [13]:
Q2,R2,P2=qr(A,Val{true})

(
[-0.542718 -0.219895 … 0.19402 0.381787; -0.0337207 -0.0136987 … -0.293091 0.307967; … ; -0.0059344 0.659774 … 0.368526 0.481772; -0.244422 0.123151 … -0.589246 0.422032],

[-1.7721 -0.785872 … -1.31023 -1.19435; 0.0 1.13428 … 0.454493 0.463436; … ; 0.0 0.0 … -0.59643 -0.211044; 0.0 0.0 … 0.0 0.45358],

[4,1,2,5,3])

In [14]:
Q2*R2-A[:,P2]

8×5 Array{Float64,2}:
 0.0          1.11022e-16  3.05311e-16   3.88578e-16   1.11022e-16
 6.93889e-18  2.01228e-16  0.0           5.55112e-17  -1.11022e-16
 0.0          0.0          6.93889e-17   0.0          -2.77556e-17
 1.11022e-16  8.32667e-17  1.11022e-16   2.22045e-16   0.0        
 0.0          0.0          1.11022e-16   0.0           1.11022e-16
 1.11022e-16  1.38778e-17  1.11022e-16   1.11022e-16   0.0        
 0.0          0.0          8.84709e-17  -2.77556e-17   5.55112e-17
 5.55112e-17  0.0          1.66533e-16   0.0           1.11022e-16

## Brzina

Broj računskih operacija potrebnih za računanje QR rastava matrice $n\times n$ je $O\big(\frac{4}{3}n^3\big)$ za računanje matrice $R$ i  $O\big(\frac{4}{3}n^3\big)$ za računanje matrice $Q$. 


In [22]:
n=1024
A=rand(n,n)

1024×1024 Array{Float64,2}:
 0.410922   0.676714   0.83091   …  0.215229  0.0208399   0.354748  
 0.232272   0.0197824  0.127149     0.266586  0.158605    0.0626725 
 0.295657   0.276835   0.679303     0.724286  0.477929    0.00347661
 0.146043   0.996233   0.973362     0.632448  0.811111    0.700921  
 0.061825   0.469724   0.645578     0.39306   0.42618     0.53583   
 0.15379    0.546066   0.449039  …  0.184797  0.118424    0.585097  
 0.481404   0.264733   0.829778     0.276212  0.919317    0.538355  
 0.508099   0.33141    0.515086     0.110437  0.555823    0.665329  
 0.0837506  0.572467   0.498615     0.47481   0.645745    0.527538  
 0.191543   0.800075   0.478225     0.47663   0.475818    0.903638  
 0.805134   0.310934   0.404971  …  0.279264  0.354862    0.747661  
 0.124358   0.0514984  0.530625     0.209393  0.793842    0.202251  
 0.177486   0.772825   0.617741     0.330819  0.519383    0.173045  
 ⋮                               ⋱                                  
 0.668

In [23]:
@time qr(A);

  0.291469 seconds (2.10 k allocations: 32.596 MB, 0.39% gc time)


In [20]:
@time qr(A,Val{true});

  0.062618 seconds (557 allocations: 6.307 MB)


In [18]:
@time myHouseholderQR(A);

  2.954223 seconds (29.02 k allocations: 3.358 GB, 16.66% gc time)


## Točnost

Za matrice $\hat Q$ i $\hat R$ izračunate Householder-ovom metodom vrijedi: 

\begin{align*}
\hat Q^T\hat Q& =I+E, \qquad \|E \|_2\approx \varepsilon,\\ 
\| A-\hat Q\hat R\|_2& \approx \varepsilon\|A\|_2.
\end{align*}

Također, postoji egzaktna ortogonalna matrica $Q$ za koju je 

$$\| A- Q\hat R\|_2\approx \varepsilon\|A\|_2.
$$