# QR rastav

---

__QR rastav__ matrice $A$ tipa $m\times n$,  $m\geq n$,
glasi

$$
A=QR, 
$$

pri čemu je $Q$ __ortonormirana matrica__ dimenzije $m\times m$, odnosno

$$
Q^TQ=Q Q^T=I,
$$

a $R$ je $m\times n$ gornje trokutasta matrica.

Ortonormiranu matricu kraće zovemo i __ortogonalna matrica__.

Na primjer,

\begin{align*}
\begin{bmatrix} a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33} \\
a_{41} & a_{42} & a_{43} \\
a_{51} & a_{52} & a_{53}
\end{bmatrix}=
\begin{bmatrix}
q_{11} & q_{12} & q_{13} & q_{14} & q_{15} \\
q_{21} & q_{22} & q_{23} & q_{24} & q_{25} \\
q_{31} & q_{32} & q_{33} & q_{34} & q_{35} \\
q_{41} & q_{42} & q_{43} & q_{44} & q_{45} \\
q_{51} & q_{52} & q_{53} & q_{54} & q_{55}
\end{bmatrix}
\begin{bmatrix}
r_{11} & r_{12} & r_{13} \\
0 & r_{22} & r_{23} \\
0 & 0 & r_{33} \\
0 & 0 & 0 \\
0 & 0 & 0 
\end{bmatrix}. \tag{1}
\end{align*}

S (1) je definiram i __ekonomični QR rastav__

\begin{align*}
\begin{bmatrix} a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33} \\
a_{41} & a_{42} & a_{43} \\
a_{51} & a_{52} & a_{53}
\end{bmatrix}=
\begin{bmatrix}
q_{11} & q_{12} & q_{13} \\
q_{21} & q_{22} & q_{23} \\
q_{31} & q_{32} & q_{33} \\
q_{41} & q_{42} & q_{43} \\
q_{51} & q_{52} & q_{53}
\end{bmatrix}
\begin{bmatrix}
r_{11} & r_{12} & r_{13} \\
0 & r_{22} & r_{23} \\
0 & 0 & r_{33}
\end{bmatrix}. \tag{2}
\end{align*}


Izjednačavanje stupaca počevši od prvog daje: 

\begin{align*}
t&=a_{:1}\\
r_{11}&=\|t\|_2 \\
q_{:1}&=t\frac{1}{r_{11}}\\
r_{12}&= q_{:1}^Ta_{:1} \\
t&=a_{:2}-q_{:1}r_{12} \\
r_{22}&=\|t\|_2 \\
q_{:2}&=t\frac{1}{r_{22}} \\
r_{13}&=q_{:1}^Ta_{:3} \\
r_{23}&=q_{:2}^Ta_{:3} \\
t&=a_{:3}-q_{:1}r_{13}-q_{:2}r_{23}\\
r_{33}&=\|t\|_2 \\
q_{:3}&=t\frac{1}{r_{33}}.
\end{align*}

Indukcijom slijedi __Gram-Schmidt-ov postupak ortogonalizacije__.

In [3]:
function myGramSchmidtQR{T}(A::Array{T})
    m,n=size(A)
    R=zeros(Float64,n,n)
    Q=Array{Float64}(m,n)
    R[1,1]=norm(A[:,1])
    Q[:,1]=A[:,1]/R[1,1]
    for k=2:n
        for i=1:k-1
            R[i,k]=Q[:,i]⋅A[:,k]
        end
        t=A[:,k]-sum([R[i,k]*Q[:,i] for i=1:k-1])
        R[k,k]=norm(t)
        Q[:,k]=t/R[k,k]
    end
    Q,R
end 

myGramSchmidtQR (generic function with 1 method)

In [4]:
A=rand(8,5)
Q,R=myGramSchmidtQR(A)

([0.37937 -0.155578 … 0.564879 -0.289444; 0.542646 -0.40914 … -0.326667 -0.213058; … ; 0.452375 0.312017 … -0.313019 -0.415786; 0.0165221 0.745695 … -0.0718355 -0.034669], [1.61184 1.10999 … 0.995803 1.01647; 0.0 1.21442 … 0.332929 0.45807; … ; 0.0 0.0 … 0.945702 0.461073; 0.0 0.0 … 0.0 0.688163])

In [5]:
Q

8×5 Array{Float64,2}:
 0.37937    -0.155578    -0.314217    0.564879   -0.289444
 0.542646   -0.40914      0.300542   -0.326667   -0.213058
 0.326177    0.162874    -0.119921    0.305001    0.471188
 0.276412    0.162084     0.27896    -0.424257    0.354297
 0.104558    0.319528     0.749553    0.395748   -0.332457
 0.403696   -0.00932943   0.0358295   0.203525    0.488546
 0.452375    0.312017    -0.382716   -0.313019   -0.415786
 0.0165221   0.745695    -0.095695   -0.0718355  -0.034669

In [6]:
Q'*Q

5×5 Array{Float64,2}:
  1.0          -4.09451e-16  -6.96789e-17   8.75767e-17  -3.747e-16  
 -4.09451e-16   1.0           1.11211e-15  -1.3181e-16    1.13104e-15
 -6.96789e-17   1.11211e-15   1.0          -2.84046e-16  -4.44089e-16
  8.75767e-17  -1.3181e-16   -2.84046e-16   1.0           0.0        
 -3.747e-16     1.13104e-15  -4.44089e-16   0.0           1.0        

In [7]:
R

5×5 Array{Float64,2}:
 1.61184  1.10999  1.42164   0.995803   1.01647 
 0.0      1.21442  0.648255  0.332929   0.45807 
 0.0      0.0      0.66043   0.48298   -0.156705
 0.0      0.0      0.0       0.945702   0.461073
 0.0      0.0      0.0       0.0        0.688163

In [9]:
# Rezidual
A-Q*R

8×5 Array{Float64,2}:
 0.0          0.0           0.0          -1.11022e-16   0.0        
 1.11022e-16  1.38778e-17  -1.11022e-16  -2.77556e-17   3.46945e-18
 0.0          0.0           0.0           0.0           0.0        
 0.0          0.0           0.0           1.38778e-17   0.0        
 0.0          0.0           0.0           0.0          -6.93889e-17
 0.0          0.0           0.0           0.0           0.0        
 0.0          0.0           0.0           1.38778e-17   0.0        
 0.0          0.0           0.0           0.0           0.0        

Algoritam `myGramSchmidtQR()` je numerički nestabilan pa je bolje koristiti _modificirani Gram-Schmidt-ov algoritam_ ili _Householder-ove reflektore_ ili _Givens-ove rotacije_ (vidi [Matrix Computations, poglavlje 5][GVL13]).

[GVL13]: https://books.google.hr/books?id=X5YfsuCWpxMC&printsec=frontcover&hl=hr#v=onepage&q&f=false "G. Golub and C. F Van Loan, 'Matrix Computations', 4th Edition, John Hopkins, Baltimore, 2013"

## Householderovi reflektori

__QR rastav vektora__ $x$ jednak je

$$
H \begin{bmatrix} x_1 \\ x_2 \\ \vdots \\ x_m 
\end{bmatrix}  =r,
$$

gdje je 

$$
H=I - \frac{2}{v^Tv}v v^T, \qquad  
v=\begin{bmatrix}
x_1\pm \|x\|_2 \\ x_2 \\ x_3 \\ \vdots \\ x_m
\end{bmatrix}.
$$ 

__Householderov reflektor__ $H$ je __simetrična__ i __ortogonalna__ matrica (dokažite!). Ovisno o izboru predznaka u definicije vektora $v$ vrijedi

$$
r=\begin{bmatrix} \mp \|x\| \\ 0 \\ \vdots \\ 0
\end{bmatrix}
$$

Zbog numeričke stabilnost se najčešće uzima

$$
v_1=x_1+\mathop{\mathrm{sign}} (x_1) \|x\|_2.
$$

Matrica $H$ se __ne računa eksplicitno__ već se produkt $Hx$ računa po formuli

$$
Hx=x-v\frac{2v^Tx}{v^Tv}
$$

za koju je potrebno $O(6m)$ operacija.

In [10]:
function myHouseholderVector{T}(x::Array{T})
    # Vraca v
    v=deepcopy(x)
    v[1]=x[1]+sign(x[1])*norm(x)
    v
end

myHouseholderVector (generic function with 1 method)

In [11]:
x=rand(8)
v=myHouseholderVector(x)
β=(2/(v⋅v))*(v⋅x)
x-β*v

8-element Array{Float64,1}:
 -1.93816    
  2.22045e-16
  1.11022e-16
  2.22045e-16
  6.93889e-18
  2.22045e-16
  1.11022e-16
  2.77556e-17

In [12]:
norm(x)

1.938164247390589

QR rastav matrice se računa rekurzivnim QR rastavom vektora pomoću Householderovih reflektora:

In [13]:
function myHouseholderQR{T}(A1::Array{T})
    # Vraca Q i R
    A=deepcopy(A1)
    m,n=size(A)
    # R=zeros(Float64,m,n)
    Q=eye(Float64,m,m)
    for k=1:n
        v=myHouseholderVector(A[k:m,k])
        β=(2/(v⋅v))*v
        A[k:m,k:n]=A[k:m,k:n]-β*(v'*A[k:m,k:n])
        Q[k:m,:]=Q[k:m,:]-β*(v'*Q[k:m,:])
    end
    R=triu(A)
    Q',R
end
    

myHouseholderQR (generic function with 1 method)

In [14]:
A=rand(8,5)

8×5 Array{Float64,2}:
 0.439395   0.527456   0.0285663  0.9831    0.697332 
 0.493809   0.272444   0.081249   0.594915  0.746454 
 0.0909746  0.275137   0.292681   0.277465  0.744982 
 0.121917   0.872876   0.414692   0.381815  0.0475354
 0.628275   0.155216   0.758429   0.646601  0.225423 
 0.966582   0.950689   0.223044   0.526109  0.0129389
 0.805496   0.296282   0.786151   0.114928  0.673896 
 0.557581   0.0229915  0.459101   0.114918  0.775812 

In [15]:
Q,R=myHouseholderQR(A)

([-0.265024 0.236825 … 0.503125 0.259834; -0.297844 -0.0432189 … -0.547765 -0.563679; … ; -0.48584 -0.213555 … 0.49137 -0.36991; -0.336308 -0.323698 … -0.353287 0.681458], [-1.65795 -1.06497 … -1.12727 -1.13279; 0.0 1.03543 … 0.508927 -0.119713; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0])

In [16]:
Q'*A

8×5 Array{Float64,2}:
 -1.65795      -1.06497      -1.03211      -1.12727      -1.13279    
  3.98292e-17   1.03543      -0.0446286     0.508927     -0.119713   
 -5.04834e-17  -1.57064e-16  -0.807208      0.0915894    -0.252264   
 -1.99506e-17  -2.17067e-16   2.64173e-17   0.852255      0.564048   
  7.52469e-17  -1.38135e-16   1.20228e-16  -2.64503e-17   1.01409    
 -3.86501e-17  -9.17561e-17  -8.51156e-17  -1.29287e-16  -5.55112e-17
  6.32489e-17  -2.23473e-16   9.97496e-17  -8.34504e-17  -5.55112e-17
 -7.69854e-17  -1.01645e-16  -8.23727e-17  -2.52843e-16  -1.66533e-16

In [17]:
R

8×5 Array{Float64,2}:
 -1.65795  -1.06497  -1.03211    -1.12727    -1.13279 
  0.0       1.03543  -0.0446286   0.508927   -0.119713
  0.0       0.0      -0.807208    0.0915894  -0.252264
  0.0       0.0       0.0         0.852255    0.564048
  0.0       0.0       0.0         0.0         1.01409 
  0.0       0.0       0.0         0.0         0.0     
  0.0       0.0       0.0         0.0         0.0     
  0.0       0.0       0.0         0.0         0.0     

Program `myHouseholderQR()` je ilustrativan. Profesionalni programi imaju sljedeća svojstva:

* računaju s blok matricama (uobičajena dimenzija bloka je 32 ili 64),
* izračuna se vektor $\hat v=v/v_1$. Vrijedi $\hat v_1=1$, dok se ostali elemenenti vektora $\hat v$ spremaju u strogi donji trokut matrice $A$,
* ako se traži matrica $Q$, akumulacija se vrši unatrag koristeći spremljene vektore $v$ (tako se smanjuje broj operacija),
* postoji opcija vraćanja ekonomičnog rastava,
* postoji opcija računanja s __pivotiranjem__ - u svakom koraku se na prvo mjesto dovede stupac s najvećom normom pa je 

$$
AP=QR.
$$

Vrijedi

$$
|R_{kk}|\geq |R_{k+1,k+1}|
$$

pa se može utvrditi i numerički rank matrice.

In [18]:
Q1,R1=qr(A,thin=true)

([-0.265024 0.236825 … 0.630355 0.141178; -0.297844 -0.0432189 … 0.299534 0.301958; … ; -0.48584 -0.213555 … -0.343603 0.202924; -0.336308 -0.323698 … -0.103708 0.378766], [-1.65795 -1.06497 … -1.12727 -1.13279; 0.0 1.03543 … 0.508927 -0.119713; … ; 0.0 0.0 … 0.852255 0.564048; 0.0 0.0 … 0.0 1.01409])

In [19]:
Q2,R2,P2=qr(A,Val{true})

([-0.265024 -0.332724 … 0.375052 -0.482253; -0.297844 -0.342731 … 0.3631 -0.114991; … ; -0.48584 -0.103508 … -0.330933 0.398917; -0.336308 -0.330821 … -0.0584808 0.274743], [-1.65795 -1.13279 … -1.03211 -1.12727; 0.0 -1.19353 … -0.175088 -0.332363; … ; 0.0 0.0 … -0.788784 0.177502; 0.0 0.0 … 0.0 -0.744798], [1, 5, 2, 3, 4])

In [20]:
Q2*R2-A[:,P2]

8×5 Array{Float64,2}:
 -1.11022e-16  -1.11022e-16   0.0          -2.08167e-17  -1.11022e-16
  5.55112e-17  -1.11022e-16   0.0          -1.38778e-17   0.0        
  0.0           0.0           1.11022e-16   5.55112e-17   0.0        
  0.0           0.0           0.0          -5.55112e-17   5.55112e-17
  0.0          -2.77556e-17  -1.11022e-16   0.0           0.0        
 -1.11022e-16  -7.11237e-17  -1.11022e-16  -2.77556e-17   1.11022e-16
  0.0           0.0          -5.55112e-17  -1.11022e-16  -8.32667e-17
  0.0           0.0          -6.245e-17    -5.55112e-17  -6.93889e-17

## Brzina

Broj računskih operacija potrebnih za računanje QR rastava matrice $n\times n$ je $O\big(\frac{4}{3}n^3\big)$ za računanje matrice $R$ i  $O\big(\frac{4}{3}n^3\big)$ za računanje matrice $Q$. 


In [21]:
n=1024
A=rand(n,n)

1024×1024 Array{Float64,2}:
 0.866605   0.0779306   0.0615603  …  0.199131   0.19816     0.397063 
 0.0529084  0.994249    0.159189      0.158162   0.298178    0.172508 
 0.0994712  0.15845     0.460838      0.329061   0.766573    0.525905 
 0.99793    0.830524    0.324872      0.861037   0.842216    0.754014 
 0.588075   0.347994    0.647997      0.798834   0.46645     0.878832 
 0.135255   0.662728    0.854228   …  0.686863   0.57091     0.732182 
 0.332294   0.591219    0.829191      0.540038   0.844334    0.246814 
 0.538261   0.289151    0.539448      0.52202    0.701769    0.458236 
 0.947333   0.634147    0.451286      0.191489   0.0831428   0.538249 
 0.104962   0.307512    0.542109      0.724294   0.663922    0.0999618
 0.679028   0.426258    0.989972   …  0.612185   0.311797    0.609606 
 0.527374   0.797792    0.290373      0.250077   0.583373    0.0140398
 0.054275   0.303273    0.986941      0.921986   0.634162    0.823629 
 ⋮                                 ⋱             

In [23]:
@time qr(A);

  0.292824 seconds (37 allocations: 32.564 MiB, 2.14% gc time)


In [24]:
@time qr(A,Val{true});

  0.579707 seconds (31 allocations: 24.565 MiB, 4.25% gc time)


In [25]:
@time myHouseholderQR(A);

 21.528258 seconds (37.20 k allocations: 26.755 GiB, 24.55% gc time)


## Točnost

Za matrice $\hat Q$ i $\hat R$ izračunate Householder-ovom metodom vrijedi: 

\begin{align*}
\hat Q^T\hat Q& =I+E, \qquad \|E \|_2\approx \varepsilon,\\ 
\| A-\hat Q\hat R\|_2& \approx \varepsilon\|A\|_2.
\end{align*}

Također, postoji egzaktna ortogonalna matrica $Q$ za koju je 

$$\| A- Q\hat R\|_2\approx \varepsilon\|A\|_2.
$$